### PR TITLE
by default JDatabaseMySQL::getTableColumns() second arguments is 'true',...

### PR DESCRIPTION
**Pull request by ghost**
... make it 'false' to get fields as expected

### CODE REVIEW

**Comment by elkuku** [comment]
I also found this bug while playing with this class - Seems like a "won't fix" - see: #707 :(

**Comment by chdemko** [comment]
There is an issue while trying to merge:

"Your merge target has changed since we cached the merge commit - try the merge again "

Could you update your branch to the current head?

**Comment by ghost** [comment]
that's the problem. I can't do merge either ;(
What should i do?

**Comment by chdemko** [comment]
@signotorez Could you please close this pull request and open a new one?

**Pull request closed without merging**
