### PR TITLE
Add scaffolding for checkboxes test.

### PR DESCRIPTION
**Pull request by elinw**
Replacing the messed up one

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1445
Assertions: 9956
Failures: 0
Errors: 0
Test Time: 195.861198

**Comment by eddieajau** [comment]
Would you mind just adding @since 11.3 to the docblocks.  Thanks.

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1445
Assertions: 9956
Failures: 0
Errors: 0
Test Time: 193.053777

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1445
Assertions: 9956
Failures: 0
Errors: 0
Test Time: 189.054343

**Pull request merged**
