### PR TITLE
Add tests for JTableLanguage

### PR DESCRIPTION
**Pull request by mbabker**
This pull adds unit tests for JTableLanguage.  The DDL is sync'd to the CMS #__languages table, so the pull tester will be broken since the sitename and ordering columns are added.

### CODE REVIEW

**Comment by eddieajau** [comment]
Branch needs a re-sync.

**Comment by mbabker** [comment]
Rebased to current staging.

**Comment by mbabker** [comment]
Added a update file `jos_languages_update.sql` to `tests/tmp` with the schema changes so that those who are set up to run the unit tests locally can update their databases.

**Comment by realityking** [comment]
Thank you!

**Pull request merged**
