### PR TITLE
Joomla CMS [#27630] Issue with replacePrefix -- valid only for SQLServer 

### PR DESCRIPTION
**Pull request by sseshachala**
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=27630

sorry for the confusion.

### CODE REVIEW

**Comment by hooduku** [comment]
Can any one please tell me where is that 1 warning and 1 error? I know the warnings should be less than 200 or 199.

**Comment by pasamio** [comment]
Line 685 has white space at the end, not sure where the extra is warning is triggered from with a quick examination.

If you install phpcs via PEAR (http://pear.php.net/package/PHP_CodeSniffer/), executing the following in the root of the platform should tell you what is wrong:

phpcs --standard="build/phpcs/Joomla" libraries/joomla/database/database/sqlsrv.php

**Comment by elkuku** [comment]
The warning refers to a missing scope modifier for the function replacePrefix()
The white space in line 685 is still present ;)

**Comment by sseshachala** [comment]
Can this merged in to the platform please?

**Pull request merged**
