### PR TITLE
Use the autoloader to rename form/formfield.php and form/formrule.php

### PR DESCRIPTION
**Pull request by chdemko**

### CODE REVIEW

**Comment by realityking** [comment]
Yes please! :)

**Comment by eddieajau** [comment]
Does this allow us to get rid of the `JFormHelper::loadFieldClass('list');` code as well?

**Comment by realityking** [comment]
I don't think so. For this we'd have to rename the field**s** folder to field.

**Comment by chdemko** [comment]
no because they are stored in the 'fields' folder instead of the 'field' folder (note the "s").

**Comment by eddieajau** [comment]
Ok, we can attack that another time then.

**Pull request merged**
