### PR TITLE
Add JGithubMeta object to interact with Meta API endpoint

### PR DESCRIPTION
**Pull request by mbabker**

### CODE REVIEW

**Comment by ianmacl** [comment]
There is a unit test error.  Please fix it up and ask for the request to be reopened.

**Comment by mbabker** [comment]
Any suggestions on how to get past that error?  This method is unique in that it's not strictly returning the response object, but I have it doing post processing on the implied response.  The test failure occurs because the method doesn't have the response data to process.

**Comment by dongilbert** [comment]
Can you use reflection to fake it? I'll have to take a closer look when I get back in front of a computer.

**Comment by mbabker** [comment]
No idea.  Unit testing isn't one of my stronger points, but if so, I'm all for trying.

**Comment by mbabker** [comment]
OK, it was user error. :blush:

**Comment by dongilbert** [comment]
Looks better Michael.

**Pull request merged**
