### PR TITLE
Joomla CMS [#26263] When a default value is defined, cannot save a field with an empty value 

### PR DESCRIPTION
**Pull request by chdemko**
[#26263] When a default value is defined, cannot save a field with an empty value
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26263

### CODE REVIEW

**Comment by elinw** [comment]
I'm not sure what the point of a default is if you can save without a value. I think you need to choose one or the other.

**Comment by elkuku** [comment]
**Checkstyle error details:**
libraries/joomla/form/form.php:1661
Concat operator must be surrounded by spaces
libraries/joomla/form/form.php:1661
Concat operator must be surrounded by spaces

**Comment by chdemko** [comment]
This should be also related to http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=27142

**Comment by elinw** [comment]
I think this is mainly a case where people are using default rather than preselect. For example in a list you can define which value is initially selected without making it the default. Then if the user changes it to something else that is null it can save as null. That's html/javascript. You can do it for checkboxes too.  Default is a special case of filter, something that happens later, on save, if no choice is made or no response is typed. It's similar to the integer filter which forces 0 even if the user left it blank.

**Comment by elinw** [comment]
By the way on checkbox there is an attribute checked which will preset the checkbox to checked but still allow save to null.

**Comment by eddieajau** [comment]
This is the intended behavior. If you want the ability to have "nothing", don't include a default.

**Pull request closed without merging**
