### PR TITLE
New Feed package.

### PR DESCRIPTION
**Pull request by LouisLandry**

### CODE REVIEW

**Comment by LouisLandry** [comment]
Can you reopen this?

**Comment by pasamio** [comment]
I can. Can you?

**Comment by LouisLandry** [comment]
Can you pppppplease reopen this?

**Comment by pasamio** [comment]
Looks like Jools took pity on you

**Comment by pasamio** [comment]
Jools won't reopen the issue for me though.

**Comment by mahagr** [comment]
On very quick look this looks good. The only question remaining is if it will be possible to use the old class over transition time or if the new class is backwards compatible enough to replace the old one?

**Pull request closed without merging**
