### PR TITLE
Make the log package fully autoloadable.

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by realityking** [comment]
Couldn't test locally so I hope the unit test run trough ;)

**Comment by simonharrer** [comment]
http://developer.joomla.org/pulls/pulls/1184.html states all tests run through! :)

+1 for this!

**Comment by chdemko** [comment]
@realityking , could you please keep inheritance from old class names to new ones to keep B/C

**Comment by chdemko** [comment]
I think this pull request does not maintain B/C: renaming JLogger to JLogLogger may lead to B/C issue. (if a 3rd party dev has developped a new logger, his code inherits from JLogger...)

JLogger must be defined (marked as deprecated) and inherits from JLogLogger

**Pull request merged**
