### PR TITLE
JMediawiki Package for Joomla

### PR DESCRIPTION
**Pull request by nprasath002**
JMediawiki Package for Joomla. All methods are not covered by unit tests.

### CODE REVIEW

**Comment by drmmr763** [comment]
Looking at the pull request tester there are some CS errors: http://developer.joomla.org/pulls/pulls/1624.html think you can fix those?

**Comment by nprasath002** [comment]
Fixed should be ok now. Is there a way we can run these tests externally?
How can i run the pull tester?

**Comment by elinw** [comment]
Install phpunit and phpcs locally and you can run them there.  There are some instructions on the wiki linked above.I

**Comment by eddieajau** [comment]
There are still some code style errors in this package.

http://developer.joomla.org/pulls/pulls/1624.html

If you can fix them over the weekend I'll merge the code.

**Comment by dongilbert** [comment]
Since it's line ending issues, I'll merge this and then fix them right away. Thanks for your work on this.

**Comment by dongilbert** [comment]
Cleaned everything up here: 71f3311698a0febdab9c30bf0bbc57b98fa23432

**Pull request merged**
