### PR TITLE
Implement a color field for JForm.

### PR DESCRIPTION
**Pull request by realityking**
This uses the native color picker in Opera 11 and falls back to MooRainbow in all other browsers.

### CODE REVIEW

**Comment by realityking** [comment]
This probably shouldn't be pulled until after 11.2 but I wanted some feedback ;)

**Comment by elkuku** [comment]
I believe the template guys would love it :)
+1

**Comment by LouisLandry** [comment]
Love it!

Let's do it as soon as 11.2 is out.  Great stuff as always.

**Comment by LouisLandry** [comment]
Your repository needs to be rebased according to: https://groups.google.com/d/topic/joomla-dev-framework/WpDQzYe5yRs/discussion

Our apologies but the longer we waited the worse it got.

Cheers.

**Pull request closed without merging**
