### PR TITLE
Write unit tests for the JArchive package.

### PR DESCRIPTION
**Pull request by aaronschmitz**
A few unit tests added... and some to go still.

### CODE REVIEW

**Comment by realityking** [comment]
Cool. What did you change in logo.tar and logo.zip?

**Comment by aaronschmitz** [comment]
I removed the __MACOSX folder from the zip file and some similar artifact from the tar file. The way the unit tests are written, these extra files don't get deleted after the extraction is performed.

**Comment by realityking** [comment]
Thanks. The pull looks fine to me except that it seems like you're using spaces for indentation but we use tabs. Could you fix that? Thank you.

**Comment by aaronschmitz** [comment]
The original was using spaces, and I switched it to tabs. That's why the deltas are so large.

**Comment by realityking** [comment]
Gotcha. Thanks again!

**Pull request merged**
