### PR TITLE
Fix pcntl_signal errors when trying to set a signal that is not defined

### PR DESCRIPTION
**Pull request by dusto**
Cancelled last pull request as it was against the master branch.

This checks to make sure a signal doesn't equal 0 which causes pcntl_signal to throw an error.

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1280
Assertions: 2217
Failures: 0
Errors: 0
Test Time: 54.977337

**Comment by LouisLandry** [comment]
Awesome .... thanks for that, but can you remove the example daemon script from your branch so that I can just pull the fix?  If I'm not mistaken the example is in another of your branches anyway.

Cheers!

**Comment by dusto** [comment]
I removed it.

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1280
Assertions: 2217
Failures: 0
Errors: 0
Test Time: 56.217865

**Pull request merged**
