### PR TITLE
Calendar readonly="true" status prevents loading custom calendars. 

### PR DESCRIPTION
**Pull request by infograf768**
date is always displayed as Gregorian.

### CODE REVIEW

**Comment by realityking** [comment]
Why do you wann load a GUI calendar when it's read only?

**Comment by infograf768** [comment]
Because JHtml::_('date', $value) is not used in this case and the date displayed is the db Gregorian date.
Example in CMS: edit an article. The Modified Date field will always display a Gregorian date.
In Persian for example, it should display the Jalali date.

Letting read only = "true", after the patch, displays correctly the date without the calendar icon.

(Custom calendars in J use js)
I welcome  a better solution.

**Comment by realityking** [comment]
After a brief discussion with JM we figured out the issue isn't actually the JHtml::_('date', $value) call (which is done without this patch too) but that the date conversion for those other calendars actually happens in JS, so when we don't load the JS it isn't converted.

The whole system is very ugly, but I can come up with a better one. Anyone else wiser?

**Comment by chdemko** [comment]
I think we can go on with that one

**Comment by pasamio** [comment]
So why not convert the date in PHP and change the field behaviour to output a hidden field so that saving still works and instead display a disabled input field as usual.

**Comment by pasamio** [comment]
More importantly this will introduce a bug where "read only" calendars will become writeable again.

**Comment by infograf768** [comment]
Hmm, this creates issues when changing dates in the calendars when using custom calendars

**Pull request closed without merging**
