### PR TITLE
Undefined index: CLIENT in updater/adapters/collection.php

### PR DESCRIPTION
**Pull request by WebMechanic**
As per Elin's request: commit 45c11fa2 contains my suggested patch from
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=26445

and I have no idea how to tell github to exclude the others "bundled" with this request 8-|

### CODE REVIEW

**Comment by rvsjoen** [comment]
I would probably be a good idea to clean up this branch a bit and remove the commits that do not involve libraries/joomla/updater/adapters/collection.php

**Comment by WebMechanic** [comment]
if only I knew how... the stuff from July 12 shouldn't be there anyway
any hint?

**Comment by rvsjoen** [comment]
There are a couple of ways to do this, the easiest is perhaps to simply create a new branch and use git-cherry-pick to pick the one commit you want (45c11fa2) into this new branch, followed by a git commit and a new pull request on that branch.

Another way is to do a interactive rebase against master (using 'git rebase -i upstream/master) and delete the commits that you do not want, followed by a 'git push --force' to your 45c11fa branch.

A third way would be to do a mixed git-reset to master, which will leave your changes in the working index, add only the files you want and do another commit.

**Comment by WebMechanic** [comment]
thanks - one can never have enough choices http://is.gd/L2R63K
rebase and force didn't do the trick, so I'm closing this one, nuke it, and go with a new branch.
If I can cherry-pick then why can't/won't they ? ;-)

**Pull request closed without merging**
