### PR TITLE
Rename filterinput.php and filteroutput.php files to suit autoloader.

### PR DESCRIPTION
**Pull request by chdemko**
The new autoloader allows to rename these files

### CODE REVIEW

**Comment by realityking** [comment]
Did you use git mv to move the two files? It'd be good to keep the history on those files intact.

**Comment by chdemko** [comment]
yes

**Comment by realityking** [comment]
Weird, github isn't registering this as moved files. And the history for the new files have just one entry (https://github.com/chdemko/joomla-platform/commits/filter/libraries/joomla/filter/input.php)

**Comment by robschley** [comment]
It seems to have done the same thing for https://github.com/joomla/joomla-platform/pull/589 and I used git mv.

**Comment by chdemko** [comment]
I think it's because we have written some new lines in the old files

**Comment by realityking** [comment]
Maybe we'll have to do those in two commits, sucks loosing history.

On a related note, do we rally need those stubs? I really wonder how many people use require instead of jimport().

**Pull request merged**
