### PR TITLE
JGrid: Small refactoring

### PR DESCRIPTION
**Pull request by Hackwar**
After some more thought, the function addRowCell is ill-named and should be setRowCell. I also added getter/setter for the Row Option. The unittests have been changed accordingly.

### CODE REVIEW

**Comment by Hackwar** [comment]
Also had to change the behavior of the setRowCell function to completely replace the options of the row cell.

**Comment by Hackwar** [comment]
There was a bug in the rendering of row-attributes, which was fixed in this last commit. I also cleaned up the rendering function a bit. instead of having three functions to render the header, footer and body, we now have only one function that renders table areas and only switches out the changing parts, which is less code and potentially a small performance gain.

**Comment by chdemko** [comment]
Hi Hannes,

Could you please update your branch (patch cannot be applied)

**Comment by Hackwar** [comment]
In the hopes that I did this right: The conflict should be fixed now.

**Pull request merged**
