### PR TITLE
Fix for issue #1094

### PR DESCRIPTION
**Pull request by aaronschmitz**
Cause JStream to actually iterate along the string rather than repeating the beginning.

### CODE REVIEW

**Comment by pasamio** [comment]
We take the string by reference and that is going to cause the original string to change which is probably not accepted and widely regarded as a bad idea (see strtok)

**Comment by pasamio** [comment]
To be clear, you're on the right track but we need a better way. It's aiming where possible to avoid making a copy of the string but we may end up having to do this.

**Comment by elinw** [comment]
This isn't merging cleanly anymore, will you please update your branch?

**Comment by LouisLandry** [comment]
This looks good.  @pasamio would you mind looking over this again?

**Pull request merged**
