### PR TITLE
Add a CONTRIBUTING file to the repo

### PR DESCRIPTION
**Pull request by mbabker**
GitHub allows you to have a CONTRIBUTING file in your repo, which when present, adds a notice above the input area for new issues and pull requests linking to the file and contains some guidelines for contributing (see https://github.com/joomla/joomla-cms/issues/new for an example of this).

### CODE REVIEW

**Comment by pasamio** [comment]
I think this should be called CONTRIBUTING.md instead:
https://github.com/blog/1184-contributing-guidelines

As it stands right now, I don't think it's being used. I went to create a new pull request and didn't see the notification.

**Comment by mbabker** [comment]
Came up just fine for me - https://github.com/joomla/joomla-platform/issues/new or https://github.com/joomla/joomla-platform/pull/new/joomla:staging...dianaprajescu:osm

**Comment by pasamio** [comment]
Strange, maybe it figures I should know how to contribute. I can't get it to turn up for a pull request from my own repo but in both of those links it appears.

**Comment by eddieajau** [comment]
Works for me, and nice addition!

**Pull request merged**
