### PR TITLE
Change unit test suite to use an SQLite memory database.

### PR DESCRIPTION
**Pull request by LouisLandry**
One of of my frustrations with the test suite for a while has been the necessity to spend time setting up an environment to run the simplest of tests.  Now that we have an SQLite database driver I thought it would be great to have the base test suite not require any setup or configuration to run.  You simply clone the repository and call `phpunit` to have the suite run.

To achieve this a few things had to be done:
- `tests/ddl.sql` schema file for SQLite was created
- `tests/includes/JoomlaDatabaseTestCase.php` was modified to utilize an SQLite memory database.
- To execute the URL to the JHttp test stub file must be set either as a PHP constant `JTEST_HTTP_STUB` or as an operating system environment variable `JTEST_HTTP_STUB`, otherwise those tests will be skipped.
- `tests/config.dist.php` was removed since a tests configuration isn't necessary to run the default tests.
### Things left to work through.

We still need to work out a better way of handling the (optional) testing of our database drivers against external systems.  The way it is done now is sub-optimal to put it nicely.  That fix is out of scope for this pull request, but something I hope we can address in the near future.
### Nice side effects.

One of the nice side effects of this exercise (and going forward) is the use of a non-MySQL engine for discovering cross-database problems.  Several bugs and limitations were uncovered during the process and continuing down this path will only help in this area.

### CODE REVIEW

**Comment by realityking** [comment]
Rouven likey. This runs fine on my Mac whose configuration is FUBAR for MySQL testing.

The thing that worries me a bit is that we're slashing the assertions jenkins runs to a third. Won't that greatly reduce our code coverage?

**Comment by LouisLandry** [comment]
Code coverage is not greatly reduced at all.  

With this pull request coverage for elements comes out to roughly **43.5%**.  That is actually slightly lower because Jenkins/jools hasn't been setup with the constant or environment variable to run the `JHttp` tests.

Currently _(without this pull request)_ coverage for elements comes out to roughly **44.3%**.  That includes the `JHttp` tests.

There were a lot of unnecessary duplicate assertions that were removed as part of a reworking of the tests for `JTableNested` as well as some general cleanup.  I'm quite confident there is an improvement to the quality of our tests and coverage, not a loss.

I'm really excited about the lower barrier to entry for people to run the unit tests.  The only requirement now is having SQLite3 _(which is available by default for PHP 5.3+ http://www.php.net/manual/en/sqlite3.installation.php)_ installed for PHP.  In fact, you don't even have to have MySQL installed to run the test suite.

**Comment by chdemko** [comment]
When I run the unit test with a tests/config_mysql.php file, I got some errors:

```
There were 9 failures:

1) JDatabaseMysqlTest::testGetAffectedRows
158
Failed asserting that 0 matches expected 4.

/home/chdemko/Code/php/joomla/platform/git/tests/suite/joomla/database/database/JDatabaseMySQLTest.php:159

2) JDatabaseMysqlTest::testLoadAssoc
312
null does not match expected type "array".

/home/chdemko/Code/php/joomla/platform/git/tests/suite/joomla/database/database/JDatabaseMySQLTest.php:313

3) JDatabaseMysqlTest::testLoadAssocList
339
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => Array (...)
-    1 => Array (...)
-    2 => Array (...)
-    3 => Array (...)
 )

/home/chdemko/Code/php/joomla/platform/git/tests/suite/joomla/database/database/JDatabaseMySQLTest.php:340

4) JDatabaseMysqlTest::testLoadColumn
361
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'Testing'
-    1 => 'Testing2'
-    2 => 'Testing3'
-    3 => 'Testing4'
 )

/home/chdemko/Code/php/joomla/platform/git/tests/suite/joomla/database/database/JDatabaseMySQLTest.php:362

5) JDatabaseMysqlTest::testLoadObject
408
null does not match expected type "object".

/home/chdemko/Code/php/joomla/platform/git/tests/suite/joomla/database/database/JDatabaseMySQLTest.php:409

6) JDatabaseMysqlTest::testLoadObjectList
465
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => stdClass Object (...)
-    1 => stdClass Object (...)
-    2 => stdClass Object (...)
-    3 => stdClass Object (...)
 )

/home/chdemko/Code/php/joomla/platform/git/tests/suite/joomla/database/database/JDatabaseMySQLTest.php:466

7) JDatabaseMysqlTest::testLoadResult
489
Failed asserting that null matches expected 2.

/home/chdemko/Code/php/joomla/platform/git/tests/suite/joomla/database/database/JDatabaseMySQLTest.php:490

8) JDatabaseMysqlTest::testLoadRow
515
null does not match expected type "array".

/home/chdemko/Code/php/joomla/platform/git/tests/suite/joomla/database/database/JDatabaseMySQLTest.php:516

9) JDatabaseMysqlTest::testLoadRowList
543
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => Array (...)
-    1 => Array (...)
 )

/home/chdemko/Code/php/joomla/platform/git/tests/suite/joomla/database/database/JDatabaseMySQLTest.php:544

FAILURES!
Tests: 3080, Assertions: 4427, Failures: 9, Incomplete: 673, Skipped: 149.

```

**Comment by eddieajau** [comment]
A lot of the assertions disappeared in the JTableNested tests I rebuilt from scratch. Overall code coverage was increased but some methods like "store" are a bit less on an individual level.  The reason was those tests where designed to work on the whole 1.6 sample data tree for categories (everyone knows how huge that is) and I replaced that with an 8-node tree. I don't think it's worth putting more effort into JTableNested because it's been beaten around by CMS specific additions and I'd like to replace it with a more generic mapper pattern (just not today).

**Comment by LouisLandry** [comment]
I've got some more work to do on this to increase the stability and overall robustness of our unit tests.  I'm going to close this for now, since there is no reason to do it half-way.

**Pull request closed without merging**
