### PR TITLE
JOpenstreetmap Package

### PR DESCRIPTION
**Pull request by Buddhima**
This package helps Joomla platform users to interact with Open Street Map API and exchange data easily. Information flow process is done through mostly OAuth authentication and some times Basic authentication.

### CODE REVIEW

**Comment by Buddhima** [comment]
For the functionality of this package, OAuth 1 client created by Diana is essential : https://github.com/joomla/joomla-platform/pull/1422

**Comment by Buddhima** [comment]
Hi,
I have made few commits and now it's error free code.
http://developer.joomla.org/pulls/pulls/1778.html

Please let me know if I need to do something on this.
Thanks

**Comment by dongilbert** [comment]
Looks better. One other thing is that the Pull Request needs to be made to staging, instead of to gh-pages.

I like this and hope it will get merged. I'll inspect it some more once I get more time.

PS. for full details on contributing to the platform, see here: https://github.com/joomla/joomla-platform/wiki/Contributing-to-the-Joomla-Platform

**Comment by Buddhima** [comment]
Hi,
Thank you for pointing that and I'll correct that mistake soon.

**Comment by Buddhima** [comment]
Hi,
Pull Requested is shifted to https://github.com/joomla/joomla-platform/pull/1786
Thanks !

**Pull request closed without merging**
