### PR TITLE
Namespace more of Joomla's JavaScript functions and deprecate the old one

### PR DESCRIPTION
**Pull request by realityking**
Namespace more of Joomla's JavaScript functions and deprecate the old ones.

### CODE REVIEW

**Comment by LouisLandry** [comment]
Awesome yet again Rouven.  Can you change the deprecated tags to mark deprecation at 12.1 so that people know that is when we'll remove it.  Love the work, thanks!

**Comment by realityking** [comment]
Done. Also fixed the deprecated tags already in the file.

**Comment by eddieajau** [comment]
Rouven, would you mind adding a line to the change log file about this? Thanks.

**Comment by realityking** [comment]
Sure, I'll include it in my next pull of a number of smaller things.

**Comment by eddieajau** [comment]
Thanks :)

**Comment by realityking** [comment]
I added it as part of this pull: https://github.com/joomla/joomla-platform/pull/196

**Comment by eddieajau** [comment]
Awesome, thanks!

**Pull request merged**
