### PR TITLE
Fixes error Messages in Installation not using Bootstrap markup

### PR DESCRIPTION
**Pull request by vietvh**
Related issue: https://github.com/Joomla3-Admin-template/joomla-cms/issues/22

### CODE REVIEW

**Comment by LouisLandry** [comment]
Yet another reason why the JavaScript needs to not live in the Platform repository.

**Comment by vietvh** [comment]
+1 for moving JS out of Platform repository

**Comment by LouisLandry** [comment]
Would you be interested in taking that up?  You'd need to submit a pull request to the CMS to move the JS there, and once that is done we can simply delete it all from the platform repository.  Game?

**Comment by piotr-cz** [comment]
What is the html structure of current messages?
What are available types? till 2.5 these were message, notice, error

BTW from reading the code it seems that all message types are injected with same id ('system-message').
If it's true, I think the `type` should be present in id as well, or some UID at least.

``` html
<div id="system-message-container">
    <div id="system-message" class="alert alert-{type}">
        <h4 class="alert-heading">{type}</h4>
        <div>
            <p>{item}</p>
            <p>{item}</p>
        </div>
    </div>
    <div id="system-message" class="alert alert-{type}">
        <h4 class="alert-heading">{type}</h4>
        <div>
            <p>{item}</p>
        </div>
    </div>
</div>
```

@LouisLandry
If you want to move JS out of platform, don't forget JForm is using javascript classes

**Comment by vietvh** [comment]
@piotr-cz : agree about the possible duplicated ID, look like the core output of JDocumentRendererMessage could create duplicated ID too.

"system-message" is mostly used in CSS by bluestork, hathor, beez5, beez_20; in JS by Finder and in a lot of Selenium test suite, changing it could affect a lot.

Looks like there are 4 types of message: message, error, notice, warning

@LouisLandry : I'd love to but I think someone with better understanding of overall JS structure of Joomla should handle this.

**Comment by realityking** [comment]
We don't have any of the other bootstrap modifications in the platform yet and thus it would actually use different markup than JDocumentHTMLRendererMessages.

I'm going to close this for now, we'll have to see how we'll handle bootstrap with the platform when the CMS is ready to merge.

**Comment by piotr-cz** [comment]
@vietvh 
You are right that the problem was in the javascript renderMessages function. However it seems that using
$app->enqueueMessage in php (at least in Joomla 2.5) produces correct html:

``` html
<div id="system-message-container">
    <dl id="system-message">
        <dt class="error">Error</dt>
        <dd class="error message">
            <ul>
                <li>error description</li>
            </ul>
        </dd>
        <dt class="message">Message</dt>
        <dd class="message message">
            <ul>
                <li>message description</li>
            </ul>
        </dd>
        <dt class="notice">Notice</dt>
        <dd class="notice message">
            <ul>
                <li>notice description</li>
            </ul>
        </dd>
    </dl>
</div>

```

I we were to fix the renderMessages function, it should not have big impact on current templates, as the incorrect html have been produced only by Javascript.

However IMHO each message type should be wrapped by a class 'system-message-{type}` (quite similar to what your script produces); this is much easier DOM structure to work with (appending new messages to existing queue using JS/ removing them, etc).

Now It's good opportunity to do so, as the templates have to be refactored anyway

**Comment by vietvh** [comment]
@piotr-cz: Actually I do not see many types of system message displayed at once often, just trigger them by myself and here is the output in the template7 branch 

``` html
<div id="system-message" class="alert alert-notice">
      <a class="close" data-dismiss="alert">×</a>
      <h4 class="alert-heading">Error</h4>
      <div>
         <p>Error message here</p>
      </div>
      <h4 class="alert-heading">Warning</h4>
      <div>
         <p>Warning message here </p>
      </div>
      <h4 class="alert-heading">Notice</h4>
      <div>
         <p>Notice message here </p>
      </div>
</div>
```

I'd suggest the following (which we can use Bootstrap existing class, you can manipulate the DOM easily)

``` html
<div id="system-message"> 

   <div class="alert alert-notice">
      <a class="close" data-dismiss="alert">×</a>
      <h4 class="alert-heading">Error</h4>
      <div>
         <p>Error message here</p>
      </div>
   </div>

   <div class="alert alert-warning">
      <a class="close" data-dismiss="alert">×</a>
      <h4 class="alert-heading">Warning</h4>
      <div>
         <p>Warning message here </p>
      </div>
   </div>

   <div class="alert alert-notice">
      <a class="close" data-dismiss="alert">×</a>
      <h4 class="alert-heading">Notice</h4>
      <div>
         <p>Notice message here </p>
      </div>
   </div>

</div>
```

**Comment by piotr-cz** [comment]
@vietvh
I see, where you want to get. I've been using system messages in client-side app, and came to these conclusions:
- Client-side generated messages should not be stacked together by type, pop out in own box at the time when occured (newest on top).
- It doesn't make much sense from UX standpoint to dismiss messages by stack type (dismiss all errors, all warnings etc) but one-by-one with an option to hide automatically after passed time (except errors, which are pinned).
- This is a bit different than server-side messages. These were stacked together in Joomla, as where triggered at same time.

``` html
<!-- added client-side at the time of occurance -->
<div class="alert alert-notice">
    <h4 class="alert-heading">Notice</h4>
    <p>Notice message #1</p>
</div>

<!-- added client-side at the time of occurance -->
<div class="alert alert-notice">
    <h4 class="alert-heading">Notice</h4>
    <p>Notice message #2</p>
</div>

<!-- error messages don't dismiss automatically (pinned) -->
<div class="alert alert-notice pinned">
    <h4 class="alert-heading">Error</h4>
    <p>Error messages here</p>
</div>

<!-- rendered server-side, stacked together -->
<div class="alert alert-warning">
    <h4 class="alert-heading">Warning</h4>
    <p>Warning message #1</p>
    <p>Warning message #2</p>
</div>

```

While there are many ways to do it and the look & UI functionality should be up to the template developer, probably it would help if system messages structure could have been overwritten by template overrite as you suggested in [here](https://github.com/joomla/joomla-platform/pull/1381)

**Comment by vietvh** [comment]
New pull: https://github.com/joomla/joomla-platform/pull/1420

**Pull request closed without merging**
