### PR TITLE
refactoring the JFolder class

### PR DESCRIPTION
**Pull request by chdemko**
The JFolder class open directory (opendir function) without closing them immediately which can cause some issues on some platform (maximum number of opened files)

### CODE REVIEW

**Comment by elkuku** [comment]
**Checkstyle error details:**
libraries/joomla/filesystem/folder.php:87
Expected "foreach (...)\n...{\n"; found "foreach (...) ...{\n"
libraries/joomla/filesystem/folder.php:127
Expected "foreach (...)\n...{\n"; found "foreach (...) ...{\n"
libraries/joomla/filesystem/folder.php:576
Expected "if (...)\n...{...}\n...else\n"; found "if (...)\n...{...}\n...else "
libraries/joomla/filesystem/folder.php:583
Expected "if (...)\n...{...}\n...else\n"; found "if (...)\n...{...}\n...else "
libraries/joomla/filesystem/folder.php:590
Expected "if (...)\n...{...}\n...else\n"; found "if (...) ...{...}\n...else "
libraries/joomla/filesystem/folder.php:591
Expected "if (...)\n...{...}\n...else\n"; found "if (...) ...{...}\n...else "
libraries/joomla/filesystem/folder.php:596
Expected "if (...)\n...{...}\n...else\n"; found "if (...) ...{...}\n...else "
libraries/joomla/filesystem/folder.php:606
Expected "foreach (...)\n...{\n"; found "foreach (...) ...{\n"
libraries/joomla/filesystem/folder.php:607
Expected "if (...)\n...{...}\n...else\n"; found "if (...) ...{...}\n...else "
libraries/joomla/filesystem/folder.php:619
Expected "foreach (...)\n...{\n"; found "foreach (...) ...{\n"
libraries/joomla/filesystem/folder.php:620
Expected "if (...)\n...{...}\n...else\n"; found "if (...) ...{...}\n...else "
libraries/joomla/filesystem/folder.php:621
Expected "if (...)\n...{...}\n...else\n"; found "if (...) ...{...}\n...else "
libraries/joomla/filesystem/folder.php:630
Expected "if (...)\n"; found "if (...) "
libraries/joomla/filesystem/folder.php:632
Expected "if (...)\n...{...}\n...else\n"; found "if (...) ...{...}\n...else "

**Comment by eddieajau** [comment]
Tests seem to be failing??

**Comment by chdemko** [comment]
It's because they have been ran when base code was buggy

**Comment by eddieajau** [comment]
Ok.  I'm just thinking it might be better to leave heavy refactoring until 12.x and just bandaid the errors as best we can (unless, of course, this is the bandaid...).

**Comment by chdemko** [comment]
ok closing this issue

**Pull request closed without merging**
