### PR TITLE
Fix ? Relative paths used in unit tests are compared to absolute paths

### PR DESCRIPTION
**Pull request by elkuku**
I had problems running this test on my system.
When the test is executed on its own it runs fine, as only relative paths are used. But when run inside a suite it fails.

I hope this is correct, maybe I missed something else more obvious from the setup instructions ?

### CODE REVIEW

**Comment by elkuku** [comment]
Well, at least the changes don't break joomla-jenkins tests ;-)

**Comment by elinw** [comment]
This was failing for me too, due to 
https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/factory.php#L856

Which is I think because there is no JRequest loading, but I thought it might make more sense to update the code not to use JRequest.

**Comment by elkuku** [comment]
Do you mean you also get the fatal error on JRequest when running the whole suite ?
Unit tests are really strange beasts :P

**Comment by elinw** [comment]
No you're right, I get yours when I run the whole suite and the JRequest when I run just the html.

**Comment by elkuku** [comment]
After upgrading PHPUnit to version 3.6.4 these errors disappeared

**Pull request closed without merging**
