### PR TITLE
Run the autoformatting on the unit tests.

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by realityking** [comment]
BTW we need a sniff for the new line at the end of file rule.

**Comment by elkuku** [comment]
Actually there is a sniff that should check for an empty line at the end of each file:
https://github.com/joomla/joomla-platform/blob/master/build/phpcs/Joomla/Sniffs/WhiteSpace/SuperfluousWhitespaceSniff.php#L95
If it doesn't - please report ;)

So if you run:
`phpcs --standard=build/phpcs/Joomla/ --sniffs=Joomla.WhiteSpace.SuperfluousWhitespace tests/`
That should do the trick ;)

**Comment by realityking** [comment]
I haven used phpcs in months. I was just surprised that jenkins warnings/errors didn't decrease by this pull request.

**Comment by elkuku** [comment]
hmm, not getting your point. Both pull requests are still open and wont trigger a jenkins build. Please correct me..
But the interesting question remains if there is someone who is willing to fix the [quote phpcs]6675 SNIFF VIOLATION(S) WERE FOUND IN 58 SOURCE(S)[/quote] ;)

**Comment by realityking** [comment]
Sorry I was mixing up stuff (hey it's late)

What I was really wondering is that check style reported 453 warnings and 44 errors, the same number as in many other pull requests.

**Comment by elkuku** [comment]
And this a serious bug I also believe it's very very annoying and should be fixed as soon as possible... I have an idea ianmacl/pulltester#1 what could be causing this bug but I'm not sure ;)

**Comment by elkuku** [comment]
well... at least it says "0 errors" :)

**Comment by realityking** [comment]
I feel spammed...

**Comment by eddieajau** [comment]
Nikolai, can you update the branch please.  Thanks.

**Comment by realityking** [comment]
I'm not Nikolai but done ;)

**Comment by eddieajau** [comment]
Doh, sorry. It's early :)

**Pull request merged**
