### PR TITLE
Add scaffolding for JFormFieldCheckboxes unit test

### PR DESCRIPTION
**Pull request by elinw**

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1389
Assertions: 9867
Failures: 0
Errors: 0
Test Time: 181.896809

**Comment by eddieajau** [comment]
I think this need merging with master as it's reverting recent changes in a few places.  It's probably best not to mix unrelated docblock fixes in pull requests like these.

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1422
Assertions: 9913
Failures: 0
Errors: 0
Test Time: 184.054033

**Comment by elinw** [comment]
Replacing with new branch.

**Pull request closed without merging**
