### PR TITLE
Work on replacePrefix

### PR DESCRIPTION
**Pull request by elinw**
If we want to replacePrefix and  we don't have $this->tablePrefix  we  need to get it. Thanks Gabriele for pointing out that there was a problem at https://groups.google.com/d/topic/joomla-dev-platform/3dB6LUN890E/discussion.

### CODE REVIEW

**Comment by eddieajau** [comment]
An empty table prefix is a valid value - not every database will have them. Also, calling the factory method, which I don't think is a good idea, within a loop will potentially lead to recursion, or at best performance degradation.

**Comment by elinw** [comment]
That's exactly the issue, currently the method errors out if you do not have $this->tablePrefix  (either a string or null), but it fails silently on the last iteration of the loop  (unless you echo out the results).

**Comment by eddieajau** [comment]
What's the error?

**Comment by elinw** [comment]
https://gist.github.com/1326876  shows you why I came to that solution, most likely there is something better.

Now you could say just do the factory where you are using it, which is what I did at first, but it seemed more likely to be error prone if you did that instead of putting it in the method. But I do think maybe the loop issue pushes the balance back in that direction.

**Comment by eddieajau** [comment]
Try `JFactory::getDbo()->replacePrefix('#__somename');`

**Comment by elinw** [comment]
:) Works perfectly, thanks.

**Comment by eddieajau** [comment]
If you turn on strict errors if will tell you that you can't call a non-static method statically - because it gives you unpredictable results, as you found out.

**Pull request closed without merging**
