### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by romacron**

### CODE REVIEW

**Comment by realityking** [comment]
Hi romacron,

the pull request isn't mergeable and also has some style issues. Could you please separate it into multiple pull requests? Thanks.

Also please try to use a meaningful title and description for pull requests, we use those to generate a change log.

I'm closing this one.

Rouven

**Comment by romacron** [comment]
Hello Rouven,

of course. I have an small infight with the github..

descriptions and titles: okay of course

Thanks for informing.

Am 04.04.2012 17:57, schrieb Rouven Weßling:

> Hi romacron,
> 
> the pull request isn't mergeable and also has some style issues. Could you please separate it into multiple pull requests? Thanks.
> 
> Also please try to use a meaningful title and description for pull requests, we use those to generate a change log.
> 
> I'm closing this one.
> 
> Rouven
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/joomla/joomla-platform/pull/1119#issuecomment-4956641

## 

Diese Nachricht ist ausschließlich für den/die beabsichtigte/n 
Empfänger/in bestimmt. Sie enthält vertrauliche und gegebenenfalls 
rechtlich geschützte Informationen. Sollten Sie nicht der/die 
Adressat/in sein oder diese Nachricht irrtümlich erhalten haben, bitten 
wir Sie freundlichst, sie an den/die Absender/in zurückzusenden und sie 
einschließlich aller angefertigten Kopien zu vernichten. Die Weitergabe 
und das unerlaubte Kopieren dieser Nachricht sind nicht gestattet.

This message is for the sole use of the intended recipient. It may 
contain confidential and possibly privileged information. If you are not 
the intended recipient or if you have received this message in error, we 
kindly ask you to notify the sender and destroy these messages including 
all copies thereof. Any disclosure or unauthorized copying of this 
message is strictly forbidden.

**Comment by romacron** [comment]
Hey Rouven does the last descriptions how you imagine?

gruss roman

**Comment by realityking** [comment]
Yes, they were good. Thanks!

**Pull request closed without merging**
