### PR TITLE
Move JFormFieldMedia and JFormFieldHelpsite to the CMS.

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by elinw** [comment]
Can we deal with #728 prior to doing this please.

**Comment by eddieajau** [comment]
Need to update this branch.

**Comment by realityking** [comment]
Updated the branch.

**Comment by elkuku** [comment]
I believe Mr. joomla-jenkins should learn to SCREAM in case of any anomaly to the tests....`;)`

**Pull request merged**
