### PR TITLE
Add new params to media field: preview_width / preview_height

### PR DESCRIPTION
**Pull request by benjaminpick**
Improvement of #1105 : Allowing full-size preview.

### CODE REVIEW

**Comment by timoline** [comment]
Hi, ok thx
I tested it, but directory="folder" isnt working correct for me anymore, 
I mean: when pressing select it not goes to the folder.........can you can confirm that?
if I change back the code to:(line 130)
array_shift($folder);

it works ok....but maybe it has someting todo with the getParams('com_media') setting

Also a new param "default" would be nice

default = the default image to use

**Comment by benjaminpick** [comment]
Default Image: Do you mean, the image that is shown when no image is
selected (currently none)?

Or as default value, i.e. "when no image is selected then select this
one" - this kind of default you could easily implement in your extension
(something like $param->getString('image', 'default image')).

**Comment by timoline** [comment]
Hi, I read it a few times, but I think the first one

Just show the image which is set by default, when the user select a new image then show the new image
The default value is like a placeholder

**Comment by benjaminpick** [comment]
For the directory-Folder-Bug: Which exactly are your values in the XML as well as the getParams('com_media') ? It should be a regression of #728 .

**Comment by timoline** [comment]
```
        <field
            name="logo_small"
            type="media"            
            label="COM_JOOMLEAGUE_ADMIN_CLUB_LOGO_SMALL"
            description="COM_JOOMLEAGUE_ADMIN_CLUB_LOGO_SMALL_DESC"
            class="inputbox"
            preview="yes"
            directory="/com_joomleague/database/clubs/small"/>  
```

echo JComponentHelper::getParams('com_media')->get('image_path', 'images');

images

**Comment by benjaminpick** [comment]
From documentation: "This attribute should be relative to the top level /images/ folder." http://docs.joomla.org/Media_form_field_type

**Pull request merged**
