### PR TITLE
Remove the stub files at the old locations for JString and JLog.

### PR DESCRIPTION
**Pull request by realityking**
The autoloader picks them up at the right location anyways.

### CODE REVIEW

**Comment by eddieajau** [comment]
Should we do this now or after 11.4?

**Comment by realityking** [comment]
I'll leave that for you guys to decide. The autoloader should pick up the new location without issues, but anyone who has a require or include for that file would be out of luck.

**Comment by robschley** [comment]
JString has lived in its current home since August. Not sure how long we should wait before removing these stubs.

https://github.com/joomla/joomla-platform/blob/7ac88ec3e4cb352e3099a428c71139ed7cc601ac/libraries/joomla/string/string.php

**Comment by realityking** [comment]
Well it hasn't made it to the CMS until a week ago.

IMO the question is how many people use require instead of jimport()

**Comment by eddieajau** [comment]
Let's leave it till after 11.4 (whoever merges, remove annotation in title please).

**Pull request merged**
