### PR TITLE
Added Repositories API calls for JGithub

### PR DESCRIPTION
**Pull request by Skullbock**
This small additions adds the required APIs for listing repositories using JGithub

### CODE REVIEW

**Comment by dongilbert** [comment]
This looks good - It's another needed addition. Can you add unit tests for this?

**Comment by Skullbock** [comment]
In the near future i hope to be able to. I added this class for a project i'll present at JAB13 and thought to share it since it could've been needed.

**Comment by dongilbert** [comment]
Very cool - thanks for the work. There's another pull request that
completely refactors JGithub and already contains code for fetching
repositories data, but it breaks backwards compatibility. So, we may not be
merging that here, but instead release it separately. So, yours is still
needed.

There are also going to be some code style issues due to improper spacing
in your code, but I don't have a link to provide for you to review the
errors, since the checkstyle process hasn't run yet. Once it does, I'll
post it so you can review.

**Comment by Skullbock** [comment]
Yeah i feared that, as soon as the checks are done i'll take a look at them and correct for sure. Hope to be albe to put together some Unit tests too

**Comment by elkuku** [comment]
> There's another pull request that completely refactors JGithub and already contains code for fetching repositories data, but it breaks backwards compatibility. So, we may not be merging that here, but instead release it separately. So, yours is still needed.

That's interesting info...
I assume you are talking about #1820.
Would it be possible to add a small note there regarding what you (the maintainers) are thinking about it ?

Thanks.

**Comment by eddieajau** [comment]
I'm going to close this one but will say can you work with @elkuku and his branch and let's get it updated in the Framework.

**Pull request closed without merging**
