### PR TITLE
Code Style Cleanup in Unit Test Tree

### PR DESCRIPTION
**Pull request by dongilbert**
Here's tonights round of cs-cleanup for the unit test tree.

### CODE REVIEW

**Comment by dongilbert** [comment]
@ianmacl - some of the cleanup included in this PR is duplicated in @elinw's PR #1658 - I'm not sure what to do.

**Comment by elinw** [comment]
Hi Don, I thought you were working in the legacy tree? There is a ton of clean up still needed there.  I've finished the whole main tree except for line length issues so it would be great to pull in your work on length there.  
If you would take a pull from my repository and rebase your branch over it hard  you'll be left with just the differences.

**Comment by dongilbert** [comment]
If you run phpcs on the most up to date staging branch in the legacy tree, you'll see that it is complete.

I'll rebase from your repo and then push.

**Comment by dongilbert** [comment]
I don't even know what to do anymore - I can't seem to kill all these extra commits.

**Comment by elinw** [comment]
I'm actually running phpcs constantly and there are still a few things though. 

JPathwayTest.
and a couple in jRequest

**Comment by dongilbert** [comment]
I'm not getting any. Can you export and send it to me?

**Comment by elinw** [comment]
it's just 5

JPathwayTest.php:36
36
High
SpaceBefore
WhiteSpaceBefore
JPathwayTest.php:131
131
High
SpaceBefore
WhiteSpaceBefore

JFilterInput-mock-general.php:40
40
High
SpaceBefore
WhiteSpaceBefore
JFilterInput-mock-general.php:45
45
High
SpaceBefore
WhiteSpaceBefore
JRequestGetVarTest.php:116
116
High
SpaceBefore
WhiteSpaceBefore

Then it's just those hypocritical sniffs :P.

**Comment by dongilbert** [comment]
I'm not getting any errors whatsoever. I checked those lines of those
files, and there is no issue that I can see.

What does "WhatSpaceBefore" mean in this scenario?

**Comment by elinw** [comment]
It means it needs a blank line before the if

https://github.com/joomla/joomla-platform/blob/staging/tests/suites/legacy/request/JRequestGetVarTest.php#L116

**Comment by dongilbert** [comment]
Ok - didn't know that.

How come that error isn't showing up for me? I'm running phpcs with the
Joomla standard, and it's not showing. Was the standard updated recently?

**Comment by pasamio** [comment]
It was updated a week or so ago to enforce blank lines before statements like if, return, etc. similar to the one for comments

**Comment by dongilbert** [comment]
Well that would account for it then. I'll update my local standard.

**Comment by pasamio** [comment]
On the extra commits make sure that you fetch everything and try to do a rebasing onto staging and see if that makes a difference.

**Comment by dongilbert** [comment]
How do you update an installed phpcs standard? Could I somehow link it to the coding-standards repo to have it auto update?

**Comment by dongilbert** [comment]
Got it - I forgot it was installed as a git repo and updating is as easy running `git pull origin master` from the Joomla standard root folder.

**Pull request closed without merging**
