### PR TITLE
Fix for issue 183 - allow additional characters in JFolder

### PR DESCRIPTION
**Pull request by aaronschmitz**
Allowed characters based on http://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words

Additional characters allowed in JFolder names: ()[]{}#$^+.'~`!@&=;,
Disallow : in JFolder names

### CODE REVIEW

**Comment by chdemko** [comment]
see #1007

**Comment by aaronschmitz** [comment]
Are we depreciating the current file system?

**Comment by elinw** [comment]
Christophe I don't understand the reference. Yes you have a pull request but from what i can tell first, you have not addressed this issue anywhere in your pull request (in fact JFolder and makeSafe both seem to have disappeared).  If you are asking Aaron to make a similar pull request against your repo that's fine but you need to explain that not expect people to figure that out. There's no problem with people touching the same files as long as everyone is using git correctly.

In the mean time this is a highly useful and important bug fix ( : for sure should not be in the regex).

**Comment by chdemko** [comment]
it's just a reference to the new file system because the old one will be deprecated

**Comment by elinw** [comment]
So most of us can't read minds, it's important to explain what you mean when you paste a link.
I'm not sure what the fact that it will be deprecated has to do with the bug fix though.

**Comment by aaronschmitz** [comment]
As far as I can tell https://github.com/joomla/joomla-platform/pull/1007 isn't going to be ready for a while. Do we want to get this fixed before we tag 12.2?

**Comment by LouisLandry** [comment]
Thanks Aaron!

**Pull request merged**
