### PR TITLE
Update libraries/joomla/database/driver/postgresql.php

### PR DESCRIPTION
**Pull request by jdeproost**
Take into account that pg_connect() takes the port as separate argument.

### CODE REVIEW

**Comment by eddieajau** [comment]
There are a few code style problems with this PR. Would you mind fixing them. Thanks.

http://developer.joomla.org/pulls/pulls/1838.html

**Comment by jdeproost** [comment]
Done, kind regards, Johnny 

----- Original Message -----

**Comment by dongilbert** [comment]
Any tests we could implement to protect this from causing regressions when merged? Need to make sure not to break anything existing.

**Comment by dongilbert** [comment]
This is currently unmergeable. Please rebase your changes from staging and then reopen the pull request by leaving a comment "reopen"

**Pull request closed without merging**
