### PR TITLE
Updated changelog

### PR DESCRIPTION
**Pull request by nikosdion**
Updated change log with the proposed change, as per Andrew's request at https://github.com/joomla/joomla-platform/pull/201#issuecomment-1776347

### CODE REVIEW

**Comment by eddieajau** [comment]
Thanks Nic.  Could you just do an update from joomla/joomla-platform - for some reason it doesn't want to automatically merge.  Thanks!

**Comment by nikosdion** [comment]
Hi Andrew! In theory, if I didn't do an Git-n00b mistake, my branch should be updated with everything from the staging branch and you should be able to perform the merge.

**Comment by eddieajau** [comment]
Thanks. Probably wasn't your fault. Branches can get put of sync fairly easily as we pull oth request. Fortunately though, without the pain that we used to experience in svn world ;)

**Comment by nikosdion** [comment]
Yeah, I saw what happened when I pulled the branch back to my working copy. Another change was committed on the same place of the change log and conflicted with my own. Git makes resolving merge conflicts very easy, though. Too easy, in fact! So much better than SVN. If only the CMS would go GitHub, what a joy that would be :)

**Pull request merged**
