### PR TITLE
Joomla CMS [#25291] Front end clear link for media field and file field closes form 

### PR DESCRIPTION
**Pull request by chdemko**
See http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=25291

### CODE REVIEW

**Comment by eddieajau** [comment]
Christophe, would you mind splitting the line like it was originally so it obeys the line length check style (think it's max 130 characters).

Thanks in advance.

**Comment by chdemko** [comment]
Lines length changed

**Comment by eddieajau** [comment]
Thanks. Waiting on JBS testing.

**Comment by elkuku** [comment]
**Checkstyle error details:**
libraries/joomla/form/fields/media.php:131
Concat operator must be surrounded by spaces
libraries/joomla/form/fields/media.php:131
Concat operator must be surrounded by spaces
libraries/joomla/form/fields/media.php:132
Concat operator must be surrounded by spaces
libraries/joomla/form/fields/media.php:132
Concat operator must be surrounded by spaces

**Comment by chdemko** [comment]
This has been tested successfully in JBS. Ready to commit here

**Pull request merged**
