### PR TITLE
Joomla CMS [#26360] Fixed component's parameters are not loaded during installation.

### PR DESCRIPTION
**Pull request by vietvh**
Related tracker item: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=26360

### CODE REVIEW

**Comment by LouisLandry** [comment]
This looks good to me.  @pasamio would you take a look at this and pull it if you feel comfortable with the implementation.  Thanks a bunch @vietvh.

**Comment by chdemko** [comment]
This looks good to me

**Comment by pasamio** [comment]
I'm kind of worried how this will behave with those users who have nested manifest files throughout their extension. For example a separate plugin or similar. I don't see any test cases which handle that sort of edge case and if we're changing the way manifest detection should work, we should really be looking for a variety of different situations and ensuring it behaves consistently.

**Comment by vietvh** [comment]
Could you be more specific about the nested manifest files case,? Is there any ready package so that I can test?

So far the test source that I've mainly used is /tests/_data/installer_packages in the cms trunk repository.

**Comment by pasamio** [comment]
If you have a component without a config.xml which has inside itself a second component with a config.xml, how does your patch behave? Does it default the params to the component's XML file or does it pick up the config.xml from the child component that is being shipped uncompressed as well?

**Comment by chdemko** [comment]
@vietvh Any news on this?

**Comment by vietvh** [comment]
Closed for now as it need some updates.

**Pull request closed without merging**
