### PR TITLE
Fix infinite loop when there is no error page

### PR DESCRIPTION
**Pull request by elinw**

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1420
Assertions: 9898
Failures: 1
Errors: 0
Test Time: 187.140983

**Comment by eddieajau** [comment]
How do you replicate this problem?

**Comment by elinw** [comment]
Make a platform application with an error but don't tell it to echo the errors i.e let it use the default error handling that looks for an error page. Of course, don't have any error.php files avaiable in your application (as you usually would not in a cli app).

**Comment by eddieajau** [comment]
Can you please post some example code using pastie or similar. That ensures the testers have the best chance of seeing your exact problem. Thanks.

**Comment by elinw** [comment]
Is there a reason there are no unit tests for jerror?

**Comment by LouisLandry** [comment]
No one ever wrote them :-)

**Comment by elinw** [comment]
Hm actually there are some in the trunk I guess it's more no one updated them, I guess I just dug myself a hole didn't i?

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1422
Assertions: 9913
Failures: 0
Errors: 0
Test Time: 186.927763

**Comment by elinw** [comment]
https://gist.github.com/1172723

**Comment by elinw** [comment]
replaced with new pull request

**Pull request closed without merging**
