### PR TITLE
UT 3/10: Adding unittests for application package

### PR DESCRIPTION
**Pull request by Hackwar**
Fixing issues in JController and JPathway

### CODE REVIEW

**Comment by chdemko** [comment]
With this pull request, the JController::getInstance is no longer tested (using phpunit --coverage-html /tmp/report). It was tested before.

**Comment by Hackwar** [comment]
It was not really covered by a test before, only one test ran with throwing an exception for getInstance(). I'm going to try to fill these unittests in the coming days with real tests as far as possible.

**Comment by eddieajau** [comment]
Pull not merging cleanly.

**Comment by Hackwar** [comment]
Since I f**ked up this branch, I created a new branch and a new pull request. See #907. Closing this one.

**Pull request closed without merging**
