### PR TITLE
Some code style work.

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1280
Assertions: 2217
Failures: 0
Errors: 0
Test Time: 56.706133

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 
Assertions: 
Failures: 
Errors: 
Test Time:

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1425
Assertions: 9919
Failures: 0
Errors: 0
Test Time: 194.829253

**Comment by ianmacl** [comment]
**WARNING! Pull request is not against staging!**

# Test Results

Total Tests: 
Assertions: 
Failures: 
Errors: 
Test Time:

**Comment by realityking** [comment]
Closing, will open a similar one in a sec.

**Pull request closed without merging**
