### PR TITLE
JHTMLBehavior::_calendartranslation rewritten for improved readability

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Changed test to reflect that '/' is now escaped by json_encode

### CODE REVIEW

**Comment by pasamio** [comment]
You realise that if you push up to the same branch (even with a rebase) the original pull request will be updated. You don't need to keep opening new pull requests.

**Comment by okonomiyaki3000** [comment]
Indeed, but I couldn't push because of fast-forward yadda-yadda so instead of figuring out what to do about it, I just deleted the branch and uploaded again.

**Comment by LouisLandry** [comment]
This looks great @okonomiyaki3000.  Thanks for sticking with it.  One day we'll get you sorted out on rebasing and forced pushing branches.

**Comment by pasamio** [comment]
In that particular case you need to force push to ignore the losing commits warning (git push -f repo branch [note: repo branch not required but when I'm force pushing stuff I'd like to be explicit where it's going]). Alternatively deleting and pushing again is still a valid solution and I think I've had GitHub pick up the branch again but I might be wrong. Rebasing triggers Git's internal safety mechanisms to kick into action to make sure you really meant to essentially delete commits and wipe them out - which while annoying is usually a good thing.

**Pull request merged**
