### PR TITLE
renew pull from #803

### PR DESCRIPTION
**Pull request by ghost**
by default JDatabaseMySQL::getTableColumns() second arguments is 'true'

### CODE REVIEW

**Comment by ianmacl** [comment]
Can you elaborate more on what this solves?

**Comment by chdemko** [comment]
@ianmacl see #803 and #707

**Comment by LouisLandry** [comment]
@ianmacl The issue is that the exporter needs more than just the name of the field to put together an XML document describing the schema.  By default the second argument is true which means that the result will not include whether the field is nullable, what the default value is, etc.  Explicitly setting the second argument ($typeOnly) to false, we get the rest of the field information out of the DB, which allows for correct XML being generated.

**Comment by ianmacl** [comment]
Fair enough.  I suppose we should go ahead and merge it then unless there are other objections.

**Pull request merged**
