### PR TITLE
fix for issue #27946

### PR DESCRIPTION
**Pull request by jamesmoey**

### CODE REVIEW

**Comment by chdemko** [comment]
The groups of a user are now of the form:
array($groupId1 => $groupId1, $groupId2 => $groupId2, ...)

See
https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/table/user.php#L112
https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/table/user.php#L162

You can use that code  for setUserGroups
https://gist.github.com/1751107

**Comment by jamesmoey** [comment]
Do you want me to do the changes and do another pull request? addUserToGroup method on the helper class need to be change too then.

**Comment by chdemko** [comment]
Change only your code in your branch and push it on your remote repo

**Comment by chdemko** [comment]
@jamesmoey Any news on this?

**Pull request merged**
