### PR TITLE
Fix JTableUsergroup.

### PR DESCRIPTION
**Pull request by realityking**
Another issue discovered by the CMS system tests.

### CODE REVIEW

**Comment by eddieajau** [comment]
Why are we quoting dot notation?

**Comment by realityking** [comment]
What do you mean, Andrew?

**Comment by eddieajau** [comment]
Why is this line:

```
$query->where($db->quoteName('c') . '.' . $db->quoteName('rgt') . ' <= ' . (int) $this->rgt);
```

not just:

```
$query->where('c.rgt <= ' . (int) $this->rgt);
```

It doesn't necessarily affect this pull, but I'm just wondering why all the extra work for a known case. It seems overkill.

**Comment by realityking** [comment]
Ah, gotcha.

**Pull request merged**
