### PR TITLE
Update copyright notices for 2013

### PR DESCRIPTION
**Pull request by mbabker**

### CODE REVIEW

**Comment by dongilbert** [comment]
http://wheningit.tumblr.com/post/31693200338/when-i-merge-my-own-pull-requests-part-ii

**Comment by drmmr763** [comment]
Don I'm going to waste the rest of my work day on that Tumblr. Thanks.

---

[image: Small Logo] http://www.s-go.net/
_Chad Windnagle_
s-go Consulting
_607-330-2574 x103
607-229-6260 (Cell)
Website Design - SEO - Video http://www.s-go.net/_
Follow Me: [image: Facebook] http://www.facebook.com/sgoconsulting [image:
LinkedIn] http://www.linkedin.com/in/drmmr763 [image:
Twitter]http://www.twitter.com/drmmr763

**Comment by mbabker** [comment]
Glad I wasn't doing anything productive before opening that link... LOL

**Comment by dongilbert** [comment]
Well worth it. :+1:

**Pull request merged**
