### PR TITLE
Issue #246 [Joomla! CMS Issue Tracker Item #25835] JTable:getInstance doesn't manage correctly multiple includePaths

### PR DESCRIPTION
**Pull request by tompap**
Issue #246 [Joomla! CMS Issue Tracker Item #25835] JTable:getInstance doesn't manage correctly multiple includePaths

### CODE REVIEW

**Comment by ianmacl** [comment]
So the basic idea is to include every file found with the given name?

I would think that would cause problems if somebody is trying to do overrides of any sort.

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1389
Assertions: 9867
Failures: 0
Errors: 0
Test Time: 193.526119

**Comment by LouisLandry** [comment]
I'd much rather see this approached simply by deprecating the addIncludePath method and using JLoader::discover() instead.  That will give us a much better ability to override classes and provide a much cleaner loading mechanism as well.  http://api.joomla.org/Joomla-Platform/JLoader.html#discover

**Comment by tompap** [comment]
Hello, I agree that they must be a better solution for the JPath modification. But we need a way to be able to find all the paths that contains a specific file.

Looking to the description of jTable::getInstance:
- Static method to get an instance of a JTable class if it can be found in the table include paths.

This is not the current behaviour of this function, because we just search in the first table include path that match

Another Solution, will be to add an addtionnal parameter to the function JPath::find, $multiplesearch something like that, to tell that we have not to stop on the first occurence but to search all occurence.

My choice was to create a findAll, like we have in php preg_match and preg_match_all

**Comment by eddieajau** [comment]
I agree. We need to head towards using the spl autoload features more.  The addIncludePath is really a hangover from the PHP 4 days.  Thanks for working on a solution, but it's not quite what we are looking for so I'm going to close this issue on that basis.

**Comment by tompap** [comment]
Hello, I really don't understand why you want to close this issue. 
There is a BUG currently in Joomla.

On "Core" Point of view you cannot see the bug, but for third party developer, This issue apperas a lot of time, because getInstance of JTable is not working correctly. If several components are using the same name of Table (common name like User, Content for example), the JTable is not working.

Could you explain why you want to close an existing bug ? That can be reproduced very easily ?

**Comment by eddieajau** [comment]
What you need to add in your code is this:

JLoader::register('MyTableUser', $pathToClass);

or

JLoader::discover('MyTable', $pathToTables);

That will fix your problem and be future proof.

**Pull request closed without merging**
