### PR TITLE
Implement a color field for JForm.

### PR DESCRIPTION
**Pull request by realityking**
This uses the native color picker in Opera 11 and falls back to MooRainbow in all other browsers.

Also adds the corresponding JFormRule for validation.

### CODE REVIEW

**Comment by LouisLandry** [comment]
Rock and roll :-)

**Comment by LouisLandry** [comment]
So, I pulled this, but please in the future make your pull requests against staging instead of master.

**Comment by realityking** [comment]
Ah sorry, forgot all about that. Should I change the two other pulls?

**Comment by LouisLandry** [comment]
Yes please. Thanks.

On Jul 29, 2011, at 4:48 AM, realityking
reply@reply.github.com
wrote:

**Pull request merged**
