### PR TITLE
Moving rules and fields for autoloading

### PR DESCRIPTION
**Pull request by ianmacl**
Moving JForm fields and rules to new folders so they can be autoloaded.

### CODE REVIEW

**Comment by LouisLandry** [comment]
Have we also removed the "include" paths here so that it isn't trying to add an include a folder full of things that doesn't exist.

**Comment by elinw** [comment]
@ianmacl  This can be closed now I think.

**Comment by LouisLandry** [comment]
Doesn't look like it can be closed to me.  This is still an issue it seems -- unless i'm missing something.

@ianmacl can you rebase this and double check on the include paths bit please?

**Comment by elinw** [comment]
Oh for some reason I thought Rouven had done field(s) and rule(s) but it was just rules to rule.

**Comment by LouisLandry** [comment]
@ianmacl when you get this fixed up re-open please.  Marked for 12.3 release.

**Pull request closed without merging**
