### PR TITLE
Update staging

### PR DESCRIPTION
**Pull request by infograf768**
See http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=28535

This solves the display of the Modified date

### CODE REVIEW

**Comment by realityking** [comment]
Is there a reason you don't do the same change in line 881 and 875?

Also in the future, please use a more descriptive title for pull requests. They are used the automatically generate change log.

**Comment by ianmacl** [comment]
Since this is a regression I'd like to see a test for this behaviour so that it doesn't happen again.  Also it would be helpful to have at least some explanation as to what is actually happening.

**Comment by infograf768** [comment]
What is happening is that the Modified date is displayed as full date, i.e. (
Wednesday, April 1st 2012
 instead of 'Y-m-d H:i:s', for example
2012-07-05 22:07:27

As, in some languages the "full" date is much longer than the 22 characters allowed for this field (We have some with 33), the "full" date is truncated.
We do display in 2.5.6 'Y-m-d H:i:s'.
The original patch was to solve the doubled time zone but overlooked this aspect. https://github.com/joomla/joomla-platform/pull/1293https://github.com/joomla/joomla-platform/pull/1293

The reason why lines 875 and 881 are not the same is that the Calendar field is automatically displayed as  'Y-m-d H:i:s' in 875.
See calendar.php: $this->value = $date->format('Y-m-d H:i:s', true, false);
On the Joomlacode tracker are some screenshots.

**Comment by infograf768** [comment]
Another solution is to use;
. '" value="' . (0 !== (int) $value ? self::_('date', $value, $format, null) : '') . '" ' . $attribs

**Comment by elinw** [comment]
Andrea proposed the patch. Here is her comment:

There really isn't enough room to increase the size when the screen is at the
minimum size. It sounded like the main reason the Platform changed the format
is they didn't want to make the call to the database class for the format. That
format is the same for everyone in all databases: Y-m-d H:i:s so we could just
pass the format instead. Then we don't have a b/c issue with the formatting.

I uploaded patch 4 with the change. If we do this we will also want to get the
platform to make the change as well.

**Comment by infograf768** [comment]
Can this be merged please? We need to correct it in 2.5.x and master

**Comment by realityking** [comment]
I'm merging this now but I'd really be good if someone submitted unit tests for this,

**Pull request merged**
