### PR TITLE
Deprecating JNode and JTree and switching off code coverage

### PR DESCRIPTION
**Pull request by Hackwar**
JNode and JTree are classes that are not usable. If someone ever extended these classes, he had to rewrite all methods. Thus deprecating it directly for 12.1.

### CODE REVIEW

**Comment by LouisLandry** [comment]
I'm fine with this.  Will let others comment.  In fact I'd like to nuke the entire base package.

**Comment by eddieajau** [comment]
Pull not merging cleanly.

**Comment by elinw** [comment]
Hannes are you going to clean this up? I'd just make a new branch with only the deprecations in it. I'll do it if you don't feel like it, leave a note.

**Comment by Hackwar** [comment]
I'm currently pretty busy, but I will get to this shortly after new year.

**Comment by Hackwar** [comment]
ok, took another look and I will create a new branch with just the deprecations in it.

**Comment by Hackwar** [comment]
The new request is #677 Closing this one.

**Pull request closed without merging**
