### PR TITLE
Update MooTools to version 1.4 + a bugfix in tabs.js

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 
Assertions: 
Failures: 
Errors: 
Test Time:

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1439
Assertions: 9940
Failures: 0
Errors: 0
Test Time: 194.696456

**Comment by ianmacl** [comment]
Concept is good, I suggest we wait until Mootools 1.4.1 which should be released soon.

**Comment by realityking** [comment]
Fine with me but could someone cherry-pick e2288773? Or should I make a new pull request for it

It's a fix I'd really like to see in 1.7.2.

**Comment by piotr-cz** [comment]
MooTools 1.4.1 is now available (http://mootools.net/blog/2011/10/06/mootools-core-1-4-1/).
They say it's fully backward compatible with 1.2 & 1.3

**Comment by realityking** [comment]
Fixed the tabs.js fix and update Core to 1.4.1

**Comment by piotr-cz** [comment]
Thanks!
Could we have More upgraded to 1.4.0.1?

**Comment by realityking** [comment]
This pull request has had More 1.4.0.1 from the beginning.

**Comment by infograf768** [comment]
Please Rouven, can you post a patch on the Joomalcode CMS tracker for this one?

**Comment by realityking** [comment]
MooTools: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26805 (not yet updated to 1.4.1)
Tabs: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26481 (doesn't contain the last small fix)

I'll update both when this gets finally pulled.

**Comment by realityking** [comment]
Thanks Andrew :)

**Pull request merged**
