### PR TITLE
JFolder library does not close opened directory

### PR DESCRIPTION
**Pull request by chdemko**
Moved from http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26288

### CODE REVIEW

**Comment by elinw** [comment]
According to comments in the CMS tracker this does not solve the issue and was closed ... can you please clarify if this is supposed to be close also?

http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26288

**Comment by chdemko** [comment]
This has not to be closed

**Comment by chdemko** [comment]
It seems I have made some mistakes between my fork/branches. Please do not take this pull request into account before end of august.

**Comment by elinw** [comment]
You probably need to follow Ian's instructions for rebasing that were sent to the framework mailing list.

**Comment by chdemko** [comment]
Closing the issue for the moment (coming back from holidays at the end of august)

**Pull request closed without merging**
