### PR TITLE
Correct a typo in variable name

### PR DESCRIPTION
**Pull request by davidhurley**
Fixed error in local variable reference. 

Addressed in Tracker #27561

### CODE REVIEW

**Comment by pasamio** [comment]
Have you read the docblock comment for JView::$_name ?

**Comment by davidhurley** [comment]
Yes.

**Comment by davidhurley** [comment]
Sorry, are you saying I should have updated that definition? It appears to be set as a string consistently throughout the file.

**Comment by realityking** [comment]
Somehow sometimes _name is used and sometimes name. This will confuse quite a few people. We should come up with a fix that maintains b/c.

**Comment by elkuku** [comment]
The little "detail" is found in the docblock as `@deprecated` ;)
Do you get any errors or whatever that caused you to propose the change ?

**Comment by davidhurley** [comment]
Yes, as reported in the bug tracker (referenced originally) I could not instantiate a new JView manually for inclusion because the function failed to pull the correct model. Regardless of deprecation or not I would certainly think we would want the code to be correct and fix a minor problem instead of attempting to defend an error by claiming deprecation. :)

**Comment by elkuku** [comment]
Sorry I missed the tracker ID ;)
The problem could be a change introduced about two month ago ([ref](https://github.com/joomla/joomla-platform/commit/04cd4c7ae268eceab196a15bbcce0de8d600d6b1#L1L447)) when `name` is used in `getName()` but `_name` is used in the `__construct()` function.

Could you try to change `_name` to `name` in the constructor and see if this fixes the issue ?

It would be really cool if you could post a small snippet showing "how" you are instantiating the view. Just to be sure..

@realityking: I agree ;)

**Comment by davidhurley** [comment]
Yep, I will give that a shot. 

And I'll post a short code block when I get on a computer.

**Comment by elkuku** [comment]
great :)
Another (small) observation: The docblock declaration states `@var    array` which is obviously bad - while you are on it, could you also change this to `string` ?

**Comment by davidhurley** [comment]
Yeah, I saw that and I will update it too ;)

**Comment by elkuku** [comment]
Just a small note while we are on it..

`JView::assign()` and `JView::asignRef()`

``` php
<?php
foreach (get_object_vars($arg0) as $key => $val)
{
    if (substr($key, 0, 1) != '_')
    {
        $this->$key = $val;
    }
}
```

While I never really understood the use of these functions (`$this->assignRef('foo', $foo)` vs `$this->foo = $foo` since you have to access them as `$this->foo` in your view template anyway), they might cause some trouble in the "new" approach of deprecating underscored protected member vars as they are actually setters for the class....

**Comment by davidhurley** [comment]
One example of my code calls are listed below...I am loading a custom fields view within another view on a separate model. One of my own library classes loads this function.  I'm updating the definition in JView and I'm looking into the modification of the constructor as a possible solution as well as recommended.

```
    $customFields = $customFieldModel->loadCustomFields($type, $id, $edit);
    $config['name'] = 'customfield';
    $customfieldView = new JView($config);
    $layout = self::getCustomFieldLayout($customfieldView, $type, $edit, $customLayout);
    $customfieldView->setLayout($layout);
    $customfieldView->assignRef('customFields', $customFields);
    $customfieldView->assignRef('type', $type);
    return $customfieldView;
```

**Comment by davidhurley** [comment]
Upon updating the constructor to use $this->name instead of $this->_name the function does work as anticipated. 

I am unsure what if any other implications this change would make. Obviously, $this->name is not a deprecated variable ;) so perhaps it is a better solution. I have things open and can submit an updated pull request once a conclusion is reached on which function would be better to modify. 

Ideas?

**Comment by chdemko** [comment]
See #672

**Comment by chdemko** [comment]
Fixed in #1144

**Pull request closed without merging**
