### PR TITLE
Add in robot detection

### PR DESCRIPTION
**Pull request by stefanneculai**
Fix for issue #1254.

Code and tests included.

### CODE REVIEW

**Comment by LouisLandry** [comment]
Good stuff, but why not treat it like the other detect methods and have it proxied through the magic get method?

**Comment by stefanneculai** [comment]
Oh yes, I will add that in.

**Comment by stefanneculai** [comment]
Updated and fixed some coding style problems.

**Comment by LouisLandry** [comment]
Well done.

**Pull request merged**
