### PR TITLE
UT 1/4: Adding unittests for application package

### PR DESCRIPTION
**Pull request by Hackwar**
Fixing issues in JController and JPathway

This is a fixed version of pull request #516

### CODE REVIEW

**Comment by realityking** [comment]
The ApplicationException doesn't exist anymore so we don't need a test for it.

Also JInput has move to its own package and the unit tests should go into the corresponding folder.

**Comment by realityking** [comment]
Still got 3 test failures.

**Comment by Hackwar** [comment]
Should be fixed now.

**Comment by Hackwar** [comment]
I also changed JPathway and tested it completely now. For that I added an Inspector class for JApplicationHelper, which will ultimately be used for testing that class and several other classes, too. (f.ex. JRouter)

**Comment by realityking** [comment]
Thanks!

**Pull request merged**
