### PR TITLE
Joomla CMS [#26197] Defective sessions when using msqli on php 5.1x + 

### PR DESCRIPTION
**Pull request by elinw**
Addresses a session issue in MYSQLi

http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=26197

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1280
Assertions: 2217
Failures: 0
Errors: 0
Test Time: 56.407426

**Comment by eddieajau** [comment]
Any progress on this? The pull as it stands isn't the correct solution - a database driver can't be able to close the session.

**Comment by ghost** [comment]
Depending on your point of view, simple add register_shutdown_function('session_write_close'); to either the JSession constructor or the JSessionStorageDatabase constructor.

http://us2.php.net/manual/en/function.register-shutdown-function.php

This will ensure that session_write_close is executed BEFORE destructors are called.

I'd say it should be in JSession because quite honestly, the session should always be saved before anything is destroyed.  But if you only want to enforce this override for the database storage engine, it can be placed there just as easily.

Note: this should really only be considered a stop-gap, last ditch solution.  Implementations of the Joomla! Platform, such as the Joomla! CMS really should call session_write_close before rendering the final html to unlock the session for any parallel requests.

**Comment by ghost** [comment]
Is there a process to fork a pull request, modify, and then submit that data to the original issue?

I know I can update my own pull request, but I'm curious if I can make an addendum/modification to someone else's as an alternate[so as to keep the number of issues created down]

**Comment by mahagr** [comment]
You can pull changes to your own tree (or branch) and do the changes in there. When you're ready make pull requst to the author of the original pull (or if the author isn't available, do it against main tree).

**Comment by elkuku** [comment]
You can add someone elses fork/branch as a new remote and submit a pull request to his/her repo and if (s)he merges your pull it gets included - I did this in #417 and it worked OK.
I am a gitnoob myself, so I'm not entirely sure that this is the right way but it worked ;)
hope that helps

**Comment by eddieajau** [comment]
The way I train the other engineers to do it at work is like this.

Create a remote (as Nikolai says) to the other repo. I collaborate
with Louis a lot so I added his remote like this on the command line:

git remote add louis https://github.com/LouisLandry/joomla-platform.git

That's a read-only remote, but you could add a read-write version if you want.

He'll add a remote to my repo as well.  Then, find the branch that you
want to help with and you'd do something like this:

git checkout -b test_fix staging
(create a new branch based on staging called "test_fix" based on your
local staging branch)

git pull louis test_fix
(pull in Louis's version of the branch)

... apply modifications and commit ...

git push origin test_fix
(push my local branch up to my account on github)

Now I skype Louis and tell him I've added some new coded.  He'll have
added a remote to my repo and he'll do something like this:

git checkout test_fix
git pull andrew test_fix
git push origin test_fix

Hopefully it merges ok :)  Now, if Louis has made the pull request, my
commits will show up in the diff, like you can see here:

https://github.com/joomla/joomla-platform/pull/428/commits

Does that help?

Regards,
Andrew Eddie
http://www.theartofjoomla.com - the art of becoming a Joomla developer

On 21 October 2011 08:58, Nikolai Plath
reply@reply.github.com
wrote:

**Comment by mahagr** [comment]
@eddieajau: You can actually improve you process by making a pull request to Louis (for example) inside GitHub. I've done it few times and it has a few benefits over Skyping someone. :)

First the owner will see that there's pull request to his branch (don't forget to @ mention his name). He can comment the pull request, you can answer to his questions and you can update the code if needed (improvements, conflicts). It's just like doing the same with the master repository -- really cool and useful if you want to create feature together with other people.

**Comment by eddieajau** [comment]
When you are in the same room, command line is quicker ;)

Andrew

On Saturday, 22 October 2011, Matias Griese <
reply@reply.github.com>
wrote:

> @eddieajau: You can actually improve you process by making a pull request
> to Louis inside GitHub. I've done it few times and it has a few benefits
> over Skyping someone. :)
> 
> First the owner will see that there's pull request to his branch (don't
> forget to @ mention his name). He can comment the pull request, you can
> answer to his questions and you can update the code if needed (improvements,
> conflicts). It's just like doing the same with the master repository --
> really cool and useful if you want to create feature together with other
> people.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/joomla/joomla-platform/pull/238#issuecomment-2489029

## 

Regards,
Andrew Eddie
http://learn.theartofjoomla.com - training videos for Joomla 1.7 developers

**Comment by eddieajau** [comment]
I'm going to close this one for now - I really don't think this is the right solution.  Probably needs to be raised as a standalone issue if not already.

**Pull request closed without merging**
