### PR TITLE
Accessibility: add aria-required attribute to JFormField

### PR DESCRIPTION
**Pull request by SniperSister**
The aria-required attribute should be added to any required fields that are generated via JFormField.

### CODE REVIEW

**Comment by SniperSister** [comment]
Okay, I added the attributes to the actual markup output and it seems to be working fine now.

**Comment by dongilbert** [comment]
:+1:

**Comment by realityking** [comment]
Wouldn't it be better to add required="required"? In most browsers (the notable exception being IE8) this is mapped to the corresponding ARIA state. In the CMS we already have a JS based fallback for this.

**Comment by dongilbert** [comment]
He added both in the `required="required"` and `aria-required="true"` in this PR - I think it would be best to add both, since not all browsers support mapping the required attribute to the aria attribute.

**Comment by ianmacl** [comment]
http://developer.joomla.org/pulls/pulls/1764.html

There are issues there that need to be addressed before we look at this.

**Comment by SniperSister** [comment]
I fixed the issues so it should be working now.

**Comment by dongilbert** [comment]
@SniperSister add a comment with the word "reopen" not in quotes, and it will reopen the pull request automagically. Then I can review the changes and it will update the developer.joomla.org pull tester as well (not right away though). :)

**Comment by SniperSister** [comment]
Thanks for the hint ;)

reopen

**Pull request merged**
