### PR TITLE
PostgreSQL driver for Joomla! platform [clean version].

### PR DESCRIPTION
**Pull request by gpongelli**
This driver implements inherited function from JDatabaseDriver class and add some other useful function to be able to use Joomla! on PostgreSQL database.
There is also a class that inherits from JDatabaseQuery to be able to create query object using PostgreSQL dialect.
These two classes are tested by other two classes under "test" folder.

PostgreSQL's added functions:
- getAlterDbCharacterSet, set database encoding
- getCreateDbQuery, returns a query string to create a database using $option array members
- getRandom, get a random number
- getStringPositionSQL, returns string's position inside another string
- getTableSequences, returns an array of table's sequences information
- releaseTransactionSavepoint, release given savepoint during transaction
- showTables, lists all table in database
- transactionSavepoint, creates transaction savepoint

Overridden functions:
- connected
- dropTable
- escape
- execute
- fetchArray
- fetchAssoc
- fetchObject
- freeResult
- getAffectedRows
- getCollation
- getNumRows
- getQuery
- getTableColumns
- getTableCreate
- getTableKeys
- getTableList
- getVersion
- insertid
- insertObject
- lockTable
- renameTable
- replacePrefix
- select
- setUTF
- transactionCommit
- transactionRollback
- transactionStart
- unlockTables
- updateObject

PostgreSQL database query added functions:
- limit, a possible replace for limit in setQuery
- offset, a possible replace for limit in setQuery
- forShare, lock table/row during SELECT
- forUpdate, lock table/row during SELECT
- getInsertTable, used in "indertid()" to retrieve last INSERT INTO's table name
- noWait, no wait a locked table
- returning, an INSERT INTO optional clause to returns last insert id

Added also Postgresql's exporter and importer classes and their test classes.

### CODE REVIEW

**Comment by gpongelli** [comment]
Old pull request #532 .

**Comment by gpongelli** [comment]
Why is there this error?
Can someone add more log? 

Thank you,
Eng. Gabriele Pongelli

**Comment by LouisLandry** [comment]
This stuff looks really good Gabriele.  

I'd like us to avoid creating things like:

```
tests/includes/JoomlaDatabasePostgresqlTestCase.php
tests/includes/JoomlaPostgresqlTestCase.php
```

Why do we need those things?  That sort of defeats the purpose of the abstraction layer unless I'm missing something.

**Comment by gpongelli** [comment]
I did this fist time I've approached phpunit tests, I'm trying to remember.

I've added 
<code>tests/includes/JoomlaPostgresqlTestCase.php</code>
containing <b>JoomlaPostgresqlTestCase</b>, that inheritates from <b>JoomlaTestCase</b>, because JoomlaTestCase has <b>getMockDatabase()</b>, so to get PostgreSQL mock database I've had to add this extra class.
I need PostgreSQL mock database because of quoting difference and null date difference.

I've added 
<code>tests/includes/JoomlaDatabasePostgresqlTestCase.php</code>
containing <b>JoomlaDatabasePostgresqlTestCase</b>, that  from <b>JoomlaDatabaseTestCase</b>, because the need to use another configuration file (to not touch mysql existing one), to load Postgresql's related classes in <b>setUpBeforeClass</b> and in <b>getMockDatabase</b>.

Thank you,
Eng. Gabriele Pongelli

**Comment by LouisLandry** [comment]
OK, I guess that's how it is for now, but I think we need to rethink how this part of the platform is tested long term.  That doesn't seem like it's built well enough if it requires extended classes like that.

As an aside, I installed Postgres on an Ubuntu VM I have (Postgres 8.4 was the default) and ran across a singular error.  

```
louis-laptop:sandbox louis$ phpunit tests/suite/joomla/database/
PHPUnit 3.6.10 by Sebastian Bergmann.

Configuration read from /Users/louis/Documents/Code/Joomla/Platform/sandbox/phpunit.xml.dist

...............................................................  63 / 391 ( 16%)
..................................................III.I.....II. 126 / 391 ( 32%)
.......S....................................................... 189 / 391 ( 48%)
..............................................II....I..I.I...I. 252 / 391 ( 64%)
..II......II.III......I....II...II......II.II........I..E...I.. 315 / 391 ( 80%)
.............................I............S...SSSSSSSSSSSSSSSSS 378 / 391 ( 96%)
SSSSSSSSSSSSS

Time: 12 seconds, Memory: 32.50Mb

There was 1 error:

1) JDatabasePostgresqlTest::testGetTableSequences
RuntimeException: JLIB_DATABASE_QUERY_FAILED
ERROR:  column info.start_value does not exist
LINE 1: ...me" AS "column","info"."data_type" AS "data_type","info"."st...
                                                             ^
SQL=SELECT "s"."relname" AS "sequence","n"."nspname" AS "schema","t"."relname" AS "table","a"."attname" AS "column","info"."data_type" AS "data_type","info"."start_value" AS "start_value","info"."minimum_value" AS "minimum_value","info"."maximum_value" AS "maximum_value","info"."increment" AS "increment","info"."cycle_option" AS "cycle_option"
FROM pg_class AS s
LEFT JOIN pg_depend d ON d.objid=s.oid AND d.classid='pg_class'::regclass AND d.refclassid='pg_class'::regclass
LEFT JOIN pg_class t ON t.oid=d.refobjid
LEFT JOIN pg_namespace n ON n.oid=t.relnamespace
LEFT JOIN pg_attribute a ON a.attrelid=t.oid AND a.attnum=d.refobjsubid
LEFT JOIN information_schema.sequences AS info ON info.sequence_name=s.relname
WHERE s.relkind='S' AND d.deptype='a' AND t.relname='jos_dbtest'

/Users/louis/Documents/Code/Joomla/Platform/sandbox/libraries/joomla/database/driver/postgresql.php:600
/Users/louis/Documents/Code/Joomla/Platform/sandbox/libraries/joomla/database/driver.php:1086
/Users/louis/Documents/Code/Joomla/Platform/sandbox/libraries/joomla/database/driver/postgresql.php:456
/Users/louis/Documents/Code/Joomla/Platform/sandbox/tests/suite/joomla/database/database/JDatabasePostgresqlTest.php:537

FAILURES!
Tests: 391, Assertions: 1177, Errors: 1, Incomplete: 31, Skipped: 32.
```

Is this a postgresql version difference perhaps?

**Comment by gpongelli** [comment]
It could be a version difference issue, that "info" table is a system table.
As you can see minimum db version is 9.1.1, 8.4 is really old.
Update it with apt-get and let me know.

Eng. Gabriele Pongelli

**Comment by gpongelli** [comment]
Louis, wait a minute, I've an idea about how to remove that two extended classes.

Eng. Gabriele Pongelli

**Comment by gpongelli** [comment]
Louis, with these commits I've removed 

<pre><code>tests/includes/JoomlaDatabasePostgresqlTestCase.php
tests/includes/JoomlaPostgresqlTestCase.php</code></pre>

files, renaming JDatabaseMock.php file and doing some changes inside that functions I've told you [here](https://github.com/joomla/joomla-platform/pull/917#issuecomment-4169518) to be database-independent.

Tell me what do you think about these changes, thank you!
Eng. Gabriele Pongelli.

**Comment by gpongelli** [comment]
This error is really strange.
I've created locally another branch from master and tried to merge this branch, all goes ok.
Why does this error happens ?

Eng. Gabriele Pongelli

**Comment by LouisLandry** [comment]
I'm not sure yet what has caused the merge error, but GitHub shows the branch as not mergable as well.  

As for PostgreSQL 8.4 being old, that may be true.  It was originally released July of 2009.  The minimum MySQL version we support is 5.1 however, and it was first released November of 2008.  Is the PostgreSQL 9 series that much improved that we want to not support 8.4 even though it is still officially still supported by the PostgreSQL project?  Just wondering what your thoughts are.

I'll take a look at the branch later today and see if I can figure out what is causing the problems.

**Comment by gpongelli** [comment]
Where does github show that this branch is not mergeable ?

I'm watching on PostgreSQL's official website, 8.4 is supported until June 2014. When I started doing this driver I installed 9.0.4 (now after it was upgraded to 9.1.1).
I remember that I saw old 8.4 hasn't some features that are handled on newer version and on MySQL driver.
I can search these informations again and reply more deeper, but I'll post them here after 1st march.

Eng. Gabriele Pongelli .

**Comment by gpongelli** [comment]
Hi Louis,
I found [here](http://www.postgresql.org/support/versioning/) that each 

<pre>Major releases usually change the internal format of system tables and data files. 
These changes are often complex, so we do not maintain backward compatibility of all stored data.</pre>

I can't find same information I found months ago, watching your tests seems that the only changes between these versions affect information_schema about sequences.

Reading official documentation about sequences ([link for 9.1](http://www.postgresql.org/docs/9.1/static/infoschema-sequences.html) and [for 8.4](http://www.postgresql.org/docs/8.4/static/infoschema-sequences.html)) I found that some information I need and use are missing (start_value, minimum_value, maximum_value, increment, cycle).
Some of them aren't implemented, only "start_value" isn't present in 8.4 and I use these informations for exporter and importer.

I don't think to support 8.4 even if it'll lives until 2014, do you have another solution?

Eng. Gabriele Pongelli.

**Comment by gpongelli** [comment]
Reading official documentation, and testing on another 9.0.5 database server I've installed, seems that this error occurs in this version too.
Do you think better solution to be compatible since 8.4 could be filter getTableSequence's information (inside driver, importer and exporter) based on which database is running ?

Thank you,
Eng. Gabriele Pongelli.

**Comment by gpongelli** [comment]
Hi Louis,
I've added a commit to let use this driver (and importer and exporter classes) with older database.
Actually to test driver, you've only to install an older version; to test exporter and importer it's necessary to change 'getVersion' return value inside setup() call.
I know it's not an automatic procedure to test, but I did to not replicate existing classes just for this simple changes.

Eng. Gabriele Pongelli.

**Comment by gpongelli** [comment]
Hi Louis,
I've tried to locally merge my branch and I've found that the conflict is made by my moving of <code>tests/includes/mocks/JDatabaseMock.php</code> to <code>tests/includes/mocks/JDatabaseGlobalMock.php</code> meanwhile someone changes JDatabaseMock.php content.
I'll try to cherry-pick that single commit into my branch, so I hope this branch will become "mergeable".

Hoping you'll answer soon,
Eng. Gabriele Pongelli.

**Comment by gpongelli** [comment]
After some tries I've found a solution: create another branch and send another pull request with explicit removing of that file, not moving it.
I think if I'll rebase these changes this branch will be unmanageable, as previous pull request about this driver.

Eng. Gabriele Pongelli.

**Pull request closed without merging**
