### PR TITLE
Make JDatabaseQuery subclasses autoloadable.

### PR DESCRIPTION
**Pull request by realityking**
There should be full backwards compatibility due to the lines added in import.php.

### CODE REVIEW

**Comment by chdemko** [comment]
See #610

**Comment by robschley** [comment]
Yes, I just spent a bunch of time updating that code. Let's not merge this yet.

**Comment by realityking** [comment]
Ok. Let's see this as a minimum solution in case the other doesn't work out for some reason. (This one should be 100% B/C BTW)

**Comment by robschley** [comment]
Merged. Thanks!

**Pull request merged**
