### PR TITLE
Don't use deprecated APIs.

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by chdemko** [comment]
JXMLElement is now deprecated. Why do you it?

**Comment by realityking** [comment]
Backwards compatibility. I was considering moving it to legacy and only using it when legacy is loaded. Do you think we should just not use it?

**Comment by LouisLandry** [comment]
Ya, let's just not use it as much as is possible.

**Comment by realityking** [comment]
Updated to remove JXMLElement from everything but JFactory::getXML().

**Pull request merged**
