### PR TITLE
Media library

### PR DESCRIPTION
**Pull request by rvsjoen**
This provides a starting point for a media library.
Louis wrote most of this, I just cleaned it up and added some functions and filters.

That being said, I literally suck at writing unit tests, so I did the best I could.

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1235
Assertions: 2169
Failures: 0
Errors: 0
Test Time: 54.646360

**Comment by LouisLandry** [comment]
Hi Rune, if you don't mind take a look at: https://github.com/LouisLandry/joomla-platform/tree/rune_media

I pulled your work on top of the latest master and did some work to get it pretty well covered in unit testing.  This one required a little creativity to test, but JImage is over 80% coverend now and looks to work very well.  If you are cool with those changes and such I'll ask someone else to review it and I think we can get it merged in soon.

**Comment by rvsjoen** [comment]
Great, looks good to me, go for it!

**Comment by LouisLandry** [comment]
OK, I created a separate pull request for this so going to close this one.  Thanks for all the help on this one Rune ... really appreciate it.

**Pull request closed without merging**
