### PR TITLE
Use require_once instead of include in JLoader

### PR DESCRIPTION
**Pull request by rvsjoen**
I do not know if there is a good reason for using include over require_once, if there is, please disregard this commit. All unit tests ran fine with this change.

### CODE REVIEW

**Comment by rvsjoen** [comment]
Well, the reason I came across this in the first place was looking at using JLoader::import() instead of require_once to load component-specific files inside a component, such as a helper using something like JLoader::import("content", JPATH_COMPONENT_ADMINISTRATOR.DS.'helpers'); which in turn fails with a "class redefinition" error if the helper class is already loaded.

I doubt this is desired behavior as there isn't really a reason as far as I can tell to ever load a file twice.

**Comment by realityking** [comment]
I should have been a little clearer, the issue isn't the _once but the use of required instead of include inside a conditional.

**Comment by rvsjoen** [comment]
Ah, that actually makes more sense, I do not mind rewriting the commit to do include_once instead of require_once.

**Comment by realityking** [comment]
I hate to be a prick but parentheses for statements aren't allowed either. (I didn't notice that you used them before, sorry)

**Comment by rvsjoen** [comment]
Alright, third time is the charm

**Pull request merged**
