### PR TITLE
ORM for jplatform

### PR DESCRIPTION
**Pull request by juliopontes**
This is my ORM for JPlataform, using Activy Records.

Original project: https://github.com/juliopontes/joomla-orm

Wiki has examples "how to use".

https://github.com/juliopontes/joomla-orm/wiki/_pages

Cheers,

Júlio Pontes - Brazil

### CODE REVIEW

**Comment by ianmacl** [comment]
**WARNING! Pull request is not against staging!**

# Test Results

Total Tests: 1420
Assertions: 9898
Failures: 0
Errors: 0
Test Time: 185.301703

**Comment by ianmacl** [comment]
**WARNING! Pull request is not against staging!**

# Test Results

Total Tests: 1420
Assertions: 9898
Failures: 0
Errors: 0
Test Time: 187.655132

**Comment by ianmacl** [comment]
**WARNING! Pull request is not against staging!**

# Test Results

Total Tests: 1420
Assertions: 9898
Failures: 0
Errors: 0
Test Time: 189.788600

**Comment by ianmacl** [comment]
**WARNING! Pull request is not against staging!**

# Test Results

Total Tests: 1420
Assertions: 9898
Failures: 0
Errors: 0
Test Time: 199.740092

**Comment by elinw** [comment]
Hi Julio, 

Would you make your pull request against the staging branch please? If you are making the request via git hub just click on the box that says master and change it to staging.

**Comment by juliopontes** [comment]
Hi Elinw, made new pull request.

**Comment by LouisLandry** [comment]
Closing this one since you opened another request against staging.

**Pull request closed without merging**
