### PR TITLE
Fixed a typo in JHttp (stream_set_timeout vs stream_settimeout) as it cau

### PR DESCRIPTION
**Pull request by nikosdion**
Fixed a typo in JHttp (stream_set_timeout vs stream_settimeout) as it caused a fatal error when using the class. Hopefully, this time I got the pull request against the correct branch.

### CODE REVIEW

**Comment by LouisLandry** [comment]
w00t!

**Comment by eddieajau** [comment]
Nice catch.  Nic, would you also mind just adding a comment to the changelog file: /docs/manual/appendices/changelog.xml

Just helps us keep track of what gets done as it happens.  Thanks :)

**Comment by nikosdion** [comment]
Hi Andrew,

Yes, I can do that - but I'm not sure how? Should I send a new pull request with the changelog edit?

**Comment by rvsjoen** [comment]
The pull request will keep up to date with your remote tracking branch, in this case 'patch-1' so as long as you push or force push to that branch, the pull request will update itself.

**Comment by nikosdion** [comment]
Thank you! I updated the branch of my pull request, but that happened after Louis merged it and closed the pull request. I am not sure if a notification is sent out in this case or if merging is possible. If it doesn't, please let me know and I'll send a new pull request.

**Comment by eddieajau** [comment]
Hi Nic. Yeah, just send a new pull request when you have a spare moment. Thanks.

**Pull request merged**
