### PR TITLE
JOpenstreetmap Package

### PR DESCRIPTION
**Pull request by Buddhima**
This package helps Joomla platform users to interact with Open Street Map API and exchange data easily. Information flow process is done through mostly OAuth authentication and some times Basic authentication.
So far, I have made few commits to make it error free code.
http://developer.joomla.org/pulls/pulls/1786.html

Happy to hear your opinions on this implementation.

Thanks !

### CODE REVIEW

**Comment by eddieajau** [comment]
@Buddhima this branch needs to be updated. If you can do that soon, I'll merge it. Thanks in advance.

**Comment by Buddhima** [comment]
@eddieajau I have updated the branch. Thanks a lot for informing.

**Comment by dongilbert** [comment]
There's still an issue with this. I think it's because we have already merged the oauth code into the repo, and it might be conflicting. Can you try pulling from staging back into your branch to resolve any merge conflicts? And then you can push an update to this, and we can merge. If you have some trouble, I'll try to make some time to help you out with the conflicts.

**Comment by Buddhima** [comment]
Hi @dongilbert , I added OAuth1 code in order to pass the tests. 
Can you please tell me how to pull from staging back into my JOsm branch?
Thanks!

**Comment by elinw** [comment]
@Buddhima try doing a rebase over the current staging branch and see what if any conflicts you get. I think they should be limited to just that one area of your code that uses the OAuth. Then deal with the conflicts individually.  Then just check that everything still works.

**Comment by Buddhima** [comment]
Hi @elinw , @eddieajau  and @dongilbert , I solved conflicts (conflicts only found in Oauth1).
Thanks for guidance.

**Pull request merged**
