### PR TITLE
Remove our custom session ID generating code if favor of session_regenerate_id().

### PR DESCRIPTION
**Pull request by realityking**
Note there's one non-optional use of session_id() left on line 624. I'm not really sure what it does so I didn't touch it for now.

I confirmed the CMS works fine with this change (tested admin login/logout). The session id changes on logout. (It doesn't on login because apparently we don't fork the session on login)

### CODE REVIEW

**Comment by eddieajau** [comment]
Couple of thoughts:
1. Should we use session_regenerate_id(true)?
2. Should we provide some opt-in backward compatibility to use the "old" way (but deprecate it) just in case we find some edge case where sites break?

**Comment by realityking** [comment]
Indeed, it should be session_regenerate_id(true). I had that in an earlier version but apparently it got lost. Fixed.

As for B/C, could we wait if something breaks?

**Comment by eddieajau** [comment]
Yeah, that's fine. Just asking the question ;)

**Comment by LouisLandry** [comment]
Love the direction all of this is going. :-)

**Pull request merged**
