### PR TITLE
Base Package: Exception

### PR DESCRIPTION
**Pull request by AmyStephen**
Replace two "return false" with Exceptions. Updated calls to modified method and unit tests.

### CODE REVIEW

**Comment by realityking** [comment]
Hi Amy,

thanks a lot for working on these. 2 points:
1. Docblocks ;) We need the throws tags
2. JUpdater also extends JAdapter, I haven't checked but I suspect it needs to be changed as well.

**Comment by AmyStephen** [comment]
The updater does use the setAdapter - but it issues a CONTINUE if it the adapter is not set. (So, don't think it needs change.)

https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/updater/updater.php#L95

Got the docblock and accidentally pulled in a cache change. Patience while I try to remove that. =)

Thanks!

**Comment by AmyStephen** [comment]
Well, look at me. I do believe I have learned how to rebase. That will come in handy since I make a lot of mistakes. ;-)

**Comment by eddieajau** [comment]
Just wondering, why is the `return false` being changed?

**Comment by LouisLandry** [comment]
I'd vote for closing this one for now.  I don't know that I think it makes sense to be throwing exceptions instead of returning false in these cases, and there isn't a real issue needing to be solved here.  Let's think it through fully before we make a move.

**Pull request closed without merging**
