### PR TITLE
Handle scriptfile for file extensions

### PR DESCRIPTION
**Pull request by mbabker**
At present, the scriptfile for file extension types isn't copied over during install, leaving it unavailable for uninstall routines.  This change sets it up so that it is installed in a manner similar to packages.

### CODE REVIEW

**Comment by pasamio** [comment]
@ErisRod good point, the changes on line 102, line 429/451, line 588 to 593 need to be reverted. This will mean that the additions on line 346 need to be reworked. I should have looked at this closer as the intent of it is to be able to put files anywhere in the file system and this breaks it. @mbabker do you mind looking into getting this resolved quickly?

**Comment by pasamio** [comment]
Alternatively, @ErisRod if you could update and put in a pull request to fix things that'd be good as well.

**Comment by mbabker** [comment]
Could someone point me to code that's broken?  I use a files extension to drop in alternate layouts for CMS templates and haven't seen an issue with install/uninstall.

**Comment by pasamio** [comment]
I assume the reason is because you're changing extension_root. Though I could be wrong, @ErisRod care to expand on your issue?

**Comment by HLeithner** [comment]
It seams that the problem was in my install xml, with the scriptfile tag using a wrong path. After changing my xml file it seams to work perfectly. Sorry for false error reporting.

**Pull request merged**
