### PR TITLE
Joomla CMS [#22103] Update /libraries/joomla/form/formfield.php

### PR DESCRIPTION
**Pull request by benharold**
Joomla CMS [#22103] JFormField::getID strips valid characters from id attributes
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=22103

### CODE REVIEW

**Comment by eddieajau** [comment]
Branch won't merge cleanly.  Needs to be updated.

**Comment by realityking** [comment]
Merging this manually wouldn't be a big issue, but someone else should decide on the merits of this change. I just don't speak regex.

**Comment by jonnsl** [comment]
I think that this is more correct

```
$id = preg_replace('/(^[^a-z]|[^\w:._-])/i', '_', $id);
```

**Comment by chdemko** [comment]
@benharold We cannot authorise the . (dot) character and : (semi-column) in id: it will forbid css styling

if id is 'abc.def-ghi_jkl:hover'

the css rule would be

```
#abc.def-ghi_jkl:hover
```

which does not correspond to an id="abc.def-ghi_jkl:hover" but corresponds to id="abc" class="def-ghi_jkl" and the mouse over the element

**Comment by jonnsl** [comment]
@chdemko
see http://www.w3.org/TR/html401/types.html#type-name
HTML5 is even more permissive http://mathiasbynens.be/notes/html5-id-class

**Comment by chdemko** [comment]
I know that but it forbids css styling

**Comment by jonnsl** [comment]
You just need to escape the special characters http://mathiasbynens.be/notes/css-escapes
http://jsfiddle.net/6262B/
http://mathiasbynens.be/demo/html5-id

**Comment by chdemko** [comment]
Is it fully compatible with all browsers?

**Comment by benharold** [comment]
Since, as Jonathan mentioned, the HTML5 spec is so widely permissive of different characters in the id tag, I would suggest that filtering the id tag has become an antiquated practice, and should be dropped altogether.

Ben

**Comment by LouisLandry** [comment]
This has been sitting for over 2 months without update and is not currently mergeable.  I'm going to close it for now.  If you want to continue the discussion please rebase the branch against current master and re-open the pull request.  Cheers.

**Pull request closed without merging**
