### PR TITLE
Updates to docs directory

### PR DESCRIPTION
**Pull request by mbabker**
- Some grammar checks
- Updated CHANGELOG

### CODE REVIEW

**Comment by eddieajau** [comment]
Michael, I apologise in advance. Ian's been working on a revised format that we can publish and I needed to pull that first.  Subsequently, I've thrown you pull out of whack.  Also, with the changelog, since we've got good HTML docs now I think what we'll do is just change that to a "revision history" page and link out to the changelog articles on developer.joomla.org for the full version.  How does that sound?  I'm sorry if this means some/a lot of your work has been wasted.

**Comment by mbabker** [comment]
It isn't a waste.  Honestly, I'm sitting in the middle of nowhere right now with nothing better to do, so little things like this are basically just time killers for me at the moment.

**Comment by mbabker** [comment]
OK, I'm merged up to master and got the changes.  I think everything's correct in terms of the change set.  The only thing I can't confirm 100% accuracy on is the changelog.xml file since the diff doesn't show because of the number of changes.

**Comment by eddieajau** [comment]
Thanks - merged. I'll fix up that changelog later.

**Pull request merged**
