### PR TITLE
Add Scaffolding for JFormFieldCheckboxes unit test

### PR DESCRIPTION
**Pull request by elinw**

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1422
Assertions: 9913
Failures: 0
Errors: 0
Test Time: 178.770282

**Comment by eddieajau** [comment]
error.php seems to have gotten mixed up in this pull??

**Comment by elinw** [comment]
we'll just pretend this never happened.

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1445
Assertions: 9956
Failures: 0
Errors: 0
Test Time: 191.878384

**Pull request closed without merging**
