### PR TITLE
Add onGetGroupsByUser event trigger

### PR DESCRIPTION
**Pull request by mdobrinic**
code style updated; JEventDispatcher used instead of JDispatcher

### CODE REVIEW

**Comment by elinw** [comment]
http://developer.joomla.org/pulls/pulls/1494.html

You have a number of code style errors and a unit test failure. 
I'm not sure what the UT failure is about but it is probably the messy intertwining of user and session.
We use tabs and not space except inside docblocks. 

Wait are these two the same?

**Comment by elinw** [comment]
If this one and the other one are the same will you close whichever one is not the one you want?

**Comment by eddieajau** [comment]
I'm going to close this one mainly because I have no idea what the problem is you are trying to solve.

**Comment by mdobrinic** [comment]
I'll look into replying before the end of the week;

I remember opening the ticket as a feature request, that I used to
establish group memberships from an external source.

Cheers!

Mark

**Pull request closed without merging**
