### PR TITLE
Allows JViewHtml->getPath to set the extension of the layout file.

### PR DESCRIPTION
**Pull request by eddieajau**
This pull allows for a different extension to be set for the layout file. Adding a default extension to `getPath` easily allows the developer to derive their own views with a new default.

### CODE REVIEW

**Comment by elinw** [comment]
:) So we can easily switch from php to phtml (and back)? +1

**Comment by eddieajau** [comment]
It's not perfect but it's a first step.  The thing it solves is you having to completely duplicate the `getPath` method which is what you have to do at the moment to get around this.  More could be done in the future but this scratches and itch.

**Comment by elinw** [comment]
That's great; it's something that has been on my mind too.

**Comment by drmmr763** [comment]
I like the sounds of this!

On Monday, December 3, 2012, elinw wrote:

> That's great; it's something that has been on my mind too.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joomla/joomla-platform/pull/1735#issuecomment-10943346.

## 

---

[image: Small Logo] http://www.s-go.net/
_Chad Windnagle_
s-go Consulting
_607-330-2574 x103
607-229-6260 (Cell)
Website Design - SEO - Video http://www.s-go.net/_
Follow Me: [image: Facebook] http://www.facebook.com/sgoconsulting [image:
LinkedIn] http://www.linkedin.com/in/drmmr763 [image:
Twitter]http://www.twitter.com/drmmr763

**Comment by pasamio** [comment]
This pull request cannot be automatically merged, looks like it'll need an update.

**Comment by eddieajau** [comment]
Fixed, but please merge https://github.com/joomla/joomla-platform/pull/1737 first.

**Comment by pasamio** [comment]
I think GitHub actually has the smarts to work out that the original one is merged but I've merged it.

**Comment by pasamio** [comment]
As an aside, there appears to have been issues with a recent pull request:
http://build.joomla.org/job/platform/1186/

**Pull request merged**
