### PR TITLE
Solving bug on JInputCLI. Instead of $data must be $args

### PR DESCRIPTION
**Pull request by fititnt**
Before:

C:\Users\fititnt\github\fititnt\jclihelper\examples>php test1.php param1 param2 -qwert --thisis=sparta
Array
(
    [0] => param1
    [1] => param2
)

After:

C:\Users\fititnt\github\fititnt\jclihelper\examples>php test1.php param1 param2 -qwert --thisis=sparta
Array
(
    [0] => param1
    [1] => param2
    [q] => 1
    [w] => 1
    [e] => 1
    [r] => 1
    [t] => 1
    [thisis] => sparta
)

C:\Users\fititnt\github\fititnt\jclihelper\examples>

### CODE REVIEW

**Comment by pasamio** [comment]
I'm confused? Whats broken?

Instead of the parsed args being well parsed and available via get(), you seem to be spamming up args and making it rather useless.

Presuming you're in a JApplicationCLI, what's wrong with the following:
$this->input->get('q');
$this->input->get('e');
$this->input->get('r');
$this->input->get('t');
$this->input->get('thisis');

**Comment by fititnt** [comment]
Humm... it should be get by input->get()? Ah, ok.
Just tried to get from something like

``` php
class Test1extends JCli {
    function __construct() {
        print_r($this->input->args);
    }
}
$cli = JCli::getInstance('Test1');
```

**Comment by fititnt** [comment]
I see again Jinput. Thanks. Will close here.

**Comment by pasamio** [comment]
Checkout the following example:
https://github.com/joomla/joomla-platform-examples/blob/master/cli/argv/run.php

**Pull request closed without merging**
