### PR TITLE
Removing unnecessary empty braces when instancing classes, CodeSniffer standard

### PR DESCRIPTION
**Pull request by elkuku**

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 
Assertions: 
Failures: 
Errors: 
Test Time:

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1440
Assertions: 9178
Failures: 2
Errors: 13
Test Time: 164.131168

**Comment by elkuku** [comment]
Wow, thats strange -- No code has changed.. I got this:

Time: 01:36, Memory: 62.00Mb
OK, but incomplete or skipped tests!
Tests: 2057, Assertions: 10009, Incomplete: 543, Skipped: 75.

Wouldn't it be good to include the failures/erros in the "Test Results" ?

**Comment by eddieajau** [comment]
Nice addition!  All tests passed here so we'll see what the build server says.

**Pull request merged**
