### PR TITLE
image codestyle Patch

### PR DESCRIPTION
**Pull request by romacron**
bridged from https://github.com/joomla/joomla-platform/pull/1137#issuecomment-7084852

### CODE REVIEW

**Comment by pasamio** [comment]
Looks like you have some CS problems still:
http://developer.joomla.org/pulls/pulls/1418.html

**Comment by pasamio** [comment]
You do realise an email copy of the comment you just deleted is sent.

**Comment by romacron** [comment]
Thank you for the information. There are a lot of codestyle errors. So 
could not imagine that 143 errors made by my self in an 10-lines function.

Am 30.07.2012 10:21, schrieb Sam Moffatt:

> You do realise an email copy of the comment you just deleted is sent.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/joomla/joomla-platform/pull/1418#issuecomment-7362671

## 

Diese Nachricht ist ausschließlich für den/die beabsichtigte/n 
Empfänger/in bestimmt. Sie enthält vertrauliche und gegebenenfalls 
rechtlich geschützte Informationen. Sollten Sie nicht der/die 
Adressat/in sein oder diese Nachricht irrtümlich erhalten haben, bitten 
wir Sie freundlichst, sie an den/die Absender/in zurückzusenden und sie 
einschließlich aller angefertigten Kopien zu vernichten. Die Weitergabe 
und das unerlaubte Kopieren dieser Nachricht sind nicht gestattet.

This message is for the sole use of the intended recipient. It may 
contain confidential and possibly privileged information. If you are not 
the intended recipient or if you have received this message in error, we 
kindly ask you to notify the sender and destroy these messages including 
all copies thereof. Any disclosure or unauthorized copying of this 
message is strictly forbidden.

**Comment by realityking** [comment]
Pull request can't be merged. Please update it.

Also some CSS changes to mooRainbow made their way into it. I guess that wasn't intentional so please revert those too.

**Comment by pasamio** [comment]
There was an error around not having a comment that is all that needed to be fixed. As noted this needs a merge. The error is the more important thing and was noted on the pull tester. If you fix this pull request to be mergeable, the pull tester will eventually update and display the error for you at the bottom. From memory you just need a new line before the `@return` in the docblock to get rid of the error.

**Comment by piotr-cz** [comment]
Why not use magic `__destruct()` for method name instead?
See [LouisLandry comment in previous PR](https://github.com/joomla/joomla-platform/pull/1137#issuecomment-5182755)

**Comment by LouisLandry** [comment]
@romacron I'd like to get this work merged, so would appreciate it if you could do the following:
1. Rebase the branch (hopefully squashing the extra commits).  7 commits for 24 lines changed seems a bit much.
2. I'd like you to use `__destruct()` instead of `destroy()`.
3. Using the classes destructor means you don't need to throw the exception if the handle is not yet loaded.

In it's current state the branch isn't mergeable, and if you can get those things done we can get this work merged into the platform pretty quickly.  I'm going to set it for the 12.3 milestone in a couple of months, so hopefully you can get to it by then.

Thanks!

_Note: I'm going to close the pull request for now.  That doens't mean I am rejecting it, just that you need to fix it up before we can review it further.  As soon as you have it fixed up feel free to re-open the pull request and we'll get it sorted out._

**Pull request closed without merging**
