### PR TITLE
UT 8/10: Adding unittests for form, html, installer and language packages

### PR DESCRIPTION
**Pull request by Hackwar**
Fixing system dependency in JParameter test
Removing deprecated methods in JLanguage from code coverage

### CODE REVIEW

**Comment by Hackwar** [comment]
I've tried to find the errors that joomla-jenkins is reporting, but wasn't able to reproduce this on my virtual machine running on Ubuntu. In order to solve this, I think I need the error logs of joomla-jenkins. Maybe the errors could be posted into his comments, so that a contributor can directly fix those?

**Comment by ianmacl** [comment]
Fatal error: Class 'JElement' not found in/libraries/joomla/html/parameter/element/list.php on line 21

I plan to post error logs to a gist or somewhere, but haven't had time to implement that yet.

**Comment by Hackwar** [comment]
Lets see if this works now.

**Comment by ianmacl** [comment]
The failure is probably from the staging repo which was broken until a while ago.

**Comment by ianmacl** [comment]
Please use require_once and not JLoader in tests.

**Comment by Hackwar** [comment]
done.

**Comment by eddieajau** [comment]
Pull not merging cleanly.

**Comment by Hackwar** [comment]
Closing this pull request. There were too many changes and its going to be easier to run that create-unittests process over all of this again and start over.

**Pull request closed without merging**
