### PR TITLE
fix bug 26564

### PR DESCRIPTION
**Pull request by oc666**
JHTML user list create duplicate values in the list.

### CODE REVIEW

**Comment by LouisLandry** [comment]
Ofer, two commits for one net line change seems unnecessary.  Would you mind rebasing this and we'll get it merged.

**Comment by oc666** [comment]
Can I rebase the branch in github interface?

**Comment by Case-Berlin** [comment]
the first Patch works

**Comment by oc666** [comment]
which one??

**Comment by Case-Berlin** [comment]
b2d1e4f

**Comment by oc666** [comment]
Thanks to Rouven's support on git rebasing.
Closing this pull request replaced by https://github.com/joomla/joomla-platform/pull/996

**Pull request closed without merging**
