### PR TITLE
fix issue #1467(JHtml::calendar does not format dates on output correctly)

### PR DESCRIPTION
**Pull request by ramalama**

### CODE REVIEW

**Comment by realityking** [comment]
Is still still working with the JS calendar? With non-gregorian calendars?

**Comment by elinw** [comment]
Would you please change this title to something that describes the issue? The title is used for creating the changelog.

**Comment by ramalama** [comment]
@realityking It is still working with the DHTML JS Calendar, but I don't know how to check the non-gergorian calendars.
@elinw changed the title, hope that it's better now.

**Comment by realityking** [comment]
I suggest you talk to JM about non-gregorian calendars, he knows most about it.

You also have code style issues and a unit test failure to address: http://developer.joomla.org/pulls/pulls/1468.html

**Comment by LouisLandry** [comment]
@ramalama this pull request is no longer mergeable.  It would be great if you could rebase it (and maybe squash some of the commits) so that it is mergeable again.  Apologies for the long delay in response.  Once you get it cleaned up we can take a quick look at the internationalization issues brought up and hopefully get it merged into the platform.

_Note: I'm closing the pull request for now.  This isn't because I'm rejecting it, but because in its current state it cannot be reviewed.  Once you get it rebased and cleaned up please re-open the pull request and we'll finish the conversation on getting it merged._  Thanks!

**Comment by ramalama** [comment]
@LouisLandry I am sorry, I do not know how to rebase it and do not have time to do this these days.

**Pull request closed without merging**
