### PR TITLE
Joomla CMS [#25431] JUserHelper::getProfile does not return a profile 

### LINKED ISSUE #343: JUserHelper::getProfile does not return a profile
This is platform issue of : [ joomla Joomla! CMS Issue Tracker Item #25431] JUserHelper::getProfile does not return a profile (trackeritem-25431)
 At line 222 in libraries/joomla/user/helper.php

$data->id=$userId;
$results = $dispatcher->trigger('onContentPrepareData', array('com_users.profile', &$data));

### PR DESCRIPTION
**Pull request by gnomeontherun**
Fixes #343

It now returns an array of the profile field data stored for a given user.

See also http://joomlacode.org/gf/project/joomla/tracker/%3Faction%3DTrackerItemEdit%26tracker_item_id%3D20025/?action=TrackerItemEdit&tracker_item_id=25431

### CODE REVIEW

**Comment by eddieajau** [comment]
Hi Jeremy. Could you fix up the code style errors please.  Thanks.

**Comment by gnomeontherun** [comment]
I ran the sniffer, and got thousands of errors, mostly due to spaces for indentation. I am sorry but is there any way to find out what Jenkins claims is the 1 error?

**Comment by elinw** [comment]
I don't think it is from you, it is from something yesterday. It's showing up on  all of the tests.

**Comment by gnomeontherun** [comment]
Thanks!

**Comment by elkuku** [comment]
Actually it is yours @elinw from #566 - they should pay more attention to poor Mr. Jenkins before merging ;)

Jeremy, did you ran the sniffer over the whole repo ? Actually only the libraries folder is supposed to comply to the standards.
Try

`phpcs --standard=build/phpcs/Joomla libraries/joomla`
from the root of your platform repo.

There is also some docu if you prefer a GUI: http://docs.joomla.org/Joomla_CodeSniffer#IDE_integration

BTW: The PTI project has updated it's sources and runs fine in Eclipse Indigo now.

Happy sniffing :)

**Comment by gnomeontherun** [comment]
I ran the sniffer only on the joomla library folder, it generated a large number of indentation errors. I figure it has something to do with my configuration. Either way, I found the issue from mine was putting { on a new line, and my IDE is configured to use spaces instead of tabs so I cleared that.

**Comment by elinw** [comment]
Rofl.

**Comment by eddieajau** [comment]
Thanks Jeremy. Can you put a note on the CMS tracker that it's fixed on this side.  Thanks.

**Comment by chdemko** [comment]
Close #343

**Pull request merged**
