### PR TITLE
JGrid for dynamically generated HTML tables

### PR DESCRIPTION
**Pull request by Hackwar**
The JGrid class in this pull request allows to generate valid HTML tables. The benefit over hard-coding the table in a layout is the possibility to run it through a plugin event and thus easily extend the table.

A specific usage example:
In the backend user list view, we generate a JGrid table object and then fill it with all the current columns and rows. Now we send that table object (together with the used data) through a plugin event. A shopping cart plugin now adds a column that displays if these users have open invoices, which is added before the "Last Visit Date" column. Another plugin takes the current "Name" column and changes the content for each user to display some more statistics when you hover over the name. Last but not least, when finally in the layout, you only do a echo $table->render(); and have a valid HTML table with properly indented markup.

A few remarks to the implementation:
The class does not escape or check the data for cells or attributes. This is done on purpose, since the developer should be able to use all sorts of mark-up and not have his code changed by the class. Basically, the class is only supposed to delay the rendering of the table and not interfer with the mark-up any further.

The indentation of the generated table HTML is also not perfect. The moment a developer introduces line-breaks in his table content, the indentation is broken, but in general it should make reading the generated code a little bit easier. I also used it without the indentation and line breaks, but that became pretty much unreadable, which is why not all strings are done with single quotes, but for the indentation and line breaks with double quotes.

One thing that I'm not entirely sure of is the footer rendering. The class so far was pretty much only aimed at the current Joomla backend tables and they all have just one cell for the footer with the content, so I hard coded this behavior in there. Maybe it would be better to change this and have two rows for the footer, one for the footer with each column adressable seperately and one for the content with a columnspan. However I think if we would want to go into that direction, we can still do this in a later stage by simply adding an optional $columnName variable to the addFooter function.

Last but not least the class name. We are already using JTable and I didn't want to call it JHTMLTable, since it would then interfer with the JHTML class namespace. Who knows, maybe we want to have a JHTMLTable class in the future that generates some table content. So in the end, JGrid seemed to be the best compromise and its a reference to the Grid elements of Visual-C or Visual Basic.

### CODE REVIEW

**Comment by parthlawate** [comment]
Excellent Contribution .. More #jpositiv !

**Comment by Hackwar** [comment]
In the meantime I've been thinking about changing the class again a bit. This class would be something like JGridSimple and extend from JGrid, while JGrid would also allow to add more than one header and footer row.

@tkahl
The functionality for sorting, etc. is not included in this on purpose. The idea is to have this as a really low level base class and then either extend it or to use decorators or simply other helper functions on the object. I'm trying to decouple stuff and also keep it as flexible as possible. Nobody should say that they are restricted by this class.

**Comment by Hackwar** [comment]
Since its been a month and you seem to ignore me, I'm closing this request.

**Comment by eddieajau** [comment]
Found it.  Ok, I actually thought this was an interesting idea, but I'm not sure it's ready for a merge just yet.  I like the idea of dynamic columns.  I'd really like to see some wider discussion and use cases.  I think the full object is the right way to go, rather than a static JHtml helper - maybe even break it up into subclasses more JGridRow, JGridCell (hrm, go even as far as JHtmlTag??), and so on because I could see this baby blowing out in scope ultra quickly.  Would love to get some input from someone like Kyle Lebetter on this one because he'd like the developer to have less control over markup :)

Actually, the HTML package needs a rethink anyway so this could be a test case for that maybe?

Also, make sure you allow for heavy use of chaining (may require you to rethink the design a bit).  Could even make it mimic how mootools builds HTML so we dev's only have to learn one API to have a crack at both??

**Pull request closed without merging**
