### PR TITLE
Fixes code styling.

### PR DESCRIPTION
**Pull request by elinw**
Fix a number of codestyle issues.

### CODE REVIEW

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1389
Assertions: 9867
Failures: 0
Errors: 0
Test Time: 186.585791

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1389
Assertions: 9867
Failures: 0
Errors: 0
Test Time: 187.209739

**Comment by LouisLandry** [comment]
Needs to be updated again so it can be merged.  Apologies :-)

**Comment by elinw** [comment]
NP .... just want to get under 200/500 :P.

**Comment by ianmacl** [comment]
# Test Results

Total Tests: 1420
Assertions: 9898
Failures: 0
Errors: 0
Test Time: 191.780048

**Comment by elinw** [comment]
Should be mergeable now

**Pull request merged**
