### PR TITLE
Cleaning in the test tree

### PR DESCRIPTION
**Pull request by elinw**

### CODE REVIEW

**Comment by dongilbert** [comment]
Gettin' it DONE!!! Good job Elin. :+1:

**Comment by ianmacl** [comment]
https://github.com/elinw/joomla-platform/blob/codecleaning/tests/suites/unit/joomla/object/JObjectTest.php#L42

That method needs to be removed because we don't want empty tearDown methods and because it is a parse error (you have no method body).

**Comment by ianmacl** [comment]
Closing until parse errors are fixed.

**Comment by elinw** [comment]
reopen please (let's see what else is wrong :P)

**Comment by ianmacl** [comment]
Closing until code is fixed.

**Pull request closed without merging**
