### PR TITLE
Implement a file patcher

### PR DESCRIPTION
**Pull request by chdemko**
This could be used in the updater for patching files. Use is:

```
$patcher = JFilesystemPatcher::getInstance();
$patcher->add($udiff);
$patcher->addFile($diff_file);
$patcher->apply();
```

### CODE REVIEW

**Comment by LouisLandry** [comment]
Christophe, would you mind rebasing this?  That is a ton of merge commits for not a lot of real commits. :-)

**Comment by chdemko** [comment]
@LouisLandry Rebasing is done

**Comment by realityking** [comment]
The merge commits are still there.

**Comment by jonnsl** [comment]
try:
git checkout patcher
git reset --soft HEAD~27
git commit -a -m Implement a file patcher
git push origin patcher --force

**Comment by LouisLandry** [comment]
Beautiful.  Thanks guys.

**Pull request merged**
