### PR TITLE
Added menu to main repo.

### PR DESCRIPTION
**Pull request by ianmacl**

### CODE REVIEW

**Comment by dongilbert** [comment]
+1 - was just thinking now that we are in Markdown, that we would still need a menu.

**Comment by elkuku** [comment]
Is this auto generated in some way ?

BTW: Looks pretty cool ;)

**Comment by eddieajau** [comment]
Ah, perfect.  I was wondering how this was going to work.  @elkuku the menu isn't automatically generated, that's why it's included by hand.  If you add a new chapter, you'll have to adjust the menu.

**Comment by elkuku** [comment]
The only negative thingy I found so far is, that the navigation only works with JavaScript enabled (maybe a decent `<noscript>` tag would be good).

But a cool idea, as always from Mr. McLennan ;)

**Comment by elkuku** [comment]
Oh @ianmacl : Any chance getting the code style part in ?

**Comment by eddieajau** [comment]
@elkuku Go for it.  Maybe list it under the Appendices?

**Comment by elkuku** [comment]
Any chance of restructuring the thing ? Making the coding standards a sub folder of the manual would ease things up.

Also - currently there is a `en-US` folder. Is it realistic that there will be a translation or could this be simplified ?

I would suggest:

```
docs
 |__manual
     |__appendices
     |__chapters
     |__coding-standards
     |__menu.md
```

**Comment by eddieajau** [comment]
Well, for that matter, do we really need the `manual` container?

**Comment by elkuku** [comment]
Actually it's

```
docs
 |__assets
    |__css, js...
 |__manual
    |__md pages
```

and the `assets` folder wont fit nicely - I think..

**Comment by eddieajau** [comment]
Probably best to ask @ianmacl  what he wants to do.

**Pull request merged**
