### PR TITLE
Rename a public member in JBuffer

### PR DESCRIPTION
**Pull request by elkuku**
This will also modify the corresponding unit test

### CODE REVIEW

**Comment by realityking** [comment]
Yeah, I'm gonna get the backward compatibility club out on this one. Since this is a public member IMO it warrants some B/C treatment (which most likely means __get and __set)

**Comment by eddieajau** [comment]
Oops, sorry, didn't see your comment there Rouven.  The class seems to be loaded obscurely in the FTP client but never used.  Seems to be a left over from a by-gone era?

**Comment by realityking** [comment]
If that's the case shouldn't we just deprecate it and remove the entire class at a later date? (move to legacy now)

**Comment by eddieajau** [comment]
I think that's appropriate.

**Comment by realityking** [comment]
I just checked and it's actually used quite a bit in JClientFTP so moving it to legacy is not an option.

**Pull request merged**
