### PR TITLE
Fix issue #834: Bug in JString::parse_url

### PR DESCRIPTION
**Pull request by stefanneculai**
Bug in JString::parse_url

### CODE REVIEW

**Comment by ianmacl** [comment]
Can you please expand on the implications of this?

**Comment by stefanneculai** [comment]
Please take a look over: https://github.com/joomla/joomla-platform/issues/834

**Comment by elinw** [comment]
The autotester isn't running but his is failing a test

JStringTest::testParse_Url
Line: 629 Results should be equal
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'scheme' => 'http'
     'host' => 'joomla.org'
-    'path' => '/mytestpath/Ã�'
-    'path' => '/mytestpath/%C3%88'
  )

.../tests/suites/unit/joomla/string/JStringTest.php:629
/usr/bin/phpunit:46

You should also probably add a test for the scenario in the issue report.

**Comment by stefanneculai** [comment]
Fixed and test added in.

**Comment by chdemko** [comment]
http://a.com/?a=é
ftp://user:abcé@example.com/

does not pass the tests

See https://gist.github.com/2244092

**Comment by stefanneculai** [comment]
Indeed it was a problem with those 2. 

I have done some more tests and it seems that the parse_url from JString does nothing for UTF-8. I mean.. I have tried to return the result of parse_url and all tests pass.

Maybe this function is old and in the meanwhile PHP has solved the problems. I am using PHP 5.3.8..

**Comment by stefanneculai** [comment]
The test that was expected to fail is below.. At my end it does not fail.

$url = 'http://joomla.org/mytestpath/Ãˆ';
$expected = parse_url($url);
// Fix up path for UTF-8 characters
$expected['path'] = '/mytestpath/Ãˆ';
$actual = JString::parse_url($url);
$this->assertEquals($expected, $actual, 'Line: ' . **LINE** . ' Results should be equal');

Could anyone try my last commit with another version of PHP  or on Linux/MAC. I have used Windows.

**Comment by stefanneculai** [comment]
Any comments on this? I have just tested it on both Windows and Linux and calling the parse_url function from PHP is enough.

**Comment by chdemko** [comment]
The pull request cannot be merged. Could you try this url on windows:

```
http://mydomain.com/path/道
```

On linux php 5.4.3,

it output

```
array(3) {
  'scheme' =>
  string(4) "http"
  'host' =>
  string(12) "mydomain.com"
  'path' =>
  string(9) "/path/道"
}
```

which is correct

**Comment by stefanneculai** [comment]
Works fine on Windows too. I have created a new pull request: https://github.com/joomla/joomla-platform/pull/1285

The new one should work to be merged.

**Comment by chdemko** [comment]
See #1285

**Pull request closed without merging**
