### PR TITLE
Regex filter fits

### PR DESCRIPTION
**Pull request by Radek-Suski**
Modified the regular expression in language debugger to include dot sign as a valid KEY character and allow including an escaped double quotes inside the value (right-hand)

### CODE REVIEW

**Comment by pasamio** [comment]
Wasn't there a bug with escaped double quotes on PHP 5.2? Isn't that why we did the whole _QQ_ thing?

**Comment by realityking** [comment]
It wasn't supported in 5.2 at all AFAIK. But we don't support PHP 5.2 anymore ;)

**Comment by realityking** [comment]
Works just fine in my testing.

**Comment by Radek-Suski** [comment]
Thanks a lot :)

**Comment by pasamio** [comment]
Cool, I couldn't remember if it was PHP 5.2 or 5.3 that had it or some version of PHP 5.3. Yay for workarounds!

**Pull request merged**
