### PR TITLE
JhtmlBehavior - improve  _getJSObject

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
This function has several flaws which I think I've solved. I think that with a little more work I can eliminate it entirely as json_encode() should be used whenever possible.

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
I changed my mind about removing it entirely. There are too many cases of things being passed with the \ prefix. That practice would need to be deprecated first. It could, perhaps, be purged from all Joomla code but there's no way to know if 3rd parties are making use of it. 

In any case, it does not affect this patch as the \ behavior is still supported here.

**Comment by realityking** [comment]
Why would we remove the use of \? The whole reason that method exists is to support data types beyond those that are handled by JSON.

**Comment by okonomiyaki3000** [comment]
In my opinion, there are better ways to support types such as functions while letting json_encode take care of whatever it possibly can. But I suppose the \ solution is one that has worked well and maybe shouldn't be changed.

**Comment by LouisLandry** [comment]
Good cleanup.  If you can rebase it so that it merges cleanly I'll get it merged in this weekend.  Thanks a bunch Elijah.

**Comment by okonomiyaki3000** [comment]
Sorry, I'm on Japan time. It'll have to wait till Monday.

**Pull request closed without merging**
