### PR TITLE
MySQLi, JHTML::tabs and JHTML::getJSObject fixes

### PR DESCRIPTION
**Pull request by obsidev**
This pull request is link to two issues

Javascript Error with JHTML tabs

http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=29344

MySQLi does not display SQL errors messages anymore.

http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=29345

Regards,
Jerome @ Obsidev

### CODE REVIEW

**Comment by nikosdion** [comment]
I can confirm the tabs issue and the fix in changesets d05665a and f089977 of this PR.
I have not tested the MySQLi issue and its fix (changeset 509e3fb of this PR).

**Comment by beat** [comment]
I confirm the mysqli issue (trying to install Joomla 3.0 git on Mysql 5.0 fails (separate CMS bug) but displays no error message from mysql)

**Comment by pjwiseman** [comment]
I also confirm the tabs issue and the fix in changesets d05665a and f089977 of this PR.
I also have not tested the MySQLi issue and its fix (changeset 509e3fb of this PR).
I'd suggest that the MySQLi issue be split into a separate pull request.

**Comment by pjwiseman** [comment]
MySQLi issue was introduced by 
https://github.com/joomla/joomla-platform/commit/1971fcbdbe274d0e5f7ba77cf9c481d547ed462e

**Comment by obsidev** [comment]
I'm not very familiar with Github so I just make one Pull Request for all of my modifications.
I don't know if it's easy to change it or separate it in two different requests.

**Comment by pjwiseman** [comment]
The two issues here were replaced by the following pulls:
https://github.com/joomla/joomla-platform/pull/1554
https://github.com/joomla/joomla-platform/pull/1555

**Pull request closed without merging**
