### PR TITLE
Log Package: Minor Exception changes

### PR DESCRIPTION
**Pull request by AmyStephen**

### CODE REVIEW

**Comment by realityking** [comment]
For some reason unit tests are failing on this: http://developer.joomla.org/pulls/pulls/1088.html

**Comment by AmyStephen** [comment]
That is weird - the tests run fine on that branch for me. 

The removal shouldn't have made any change at all since we are simply removing logic that will not be reached anymore due to the changes made in the database package.

Time: 19 seconds, Memory: 157.00Mb

OK, but incomplete or skipped tests!
Tests: 3339, Assertions: 4996, Incomplete: 698, Skipped: 313.
Amy-Stephen:joomla-platform amystephen$

**Comment by AmyStephen** [comment]
When I echo the results inside of the test - this is what I get. So, not sure why but it's passing in my local environment.

$tmp->date->toISO8601()                   2012-04-01T14:05:12+00:00

$this->equalTo($date->toISO8601()    2012-04-01T14:05:12+00:00

**Comment by eddieajau** [comment]
Adding failure note for easier reference:

<pre>JLogEntryTest::testDefaultValues Line: 53. Failed asserting that two strings are equal.
 --- Expected
 +++ Actual
 @@ @@
 -'2012-03-31T21:20:57+00:00'
 +'2012-03-31T21:20:56+00:00'
 .../tests/suites/unit/joomla/log/JLogEntryTest.php:54 /usr/bin/phpunit:46</pre>


Very odd.

**Comment by AmyStephen** [comment]
Tried a new PR with recently merged core. 

Unit tests worked before and after the change. 

Will close this in favor of https://github.com/joomla/joomla-platform/pull/1100

**Comment by eddieajau** [comment]
Roger that.

**Pull request closed without merging**
