### PR TITLE
Docblocks branch

### PR DESCRIPTION
**Pull request by elinw**
This should be just the doc block edits.

### CODE REVIEW

**Comment by elinw** [comment]
This should apply cleanly now

**Comment by elinw** [comment]
ok got rid of he commits from realitykind and eddieajau which were introducing non doc block changes to he pull request.

**Comment by realityking** [comment]
I think you broke sth here. Our two commits are still part of the pull request but now there are two additional commits reverting our changes.

**Comment by elinw** [comment]
The diff shows that your stuff is untouched. It's not your commits that are reverted, it's my commit of your commits.

**Pull request merged**
