### PR TITLE
Improve JRegistry

### PR DESCRIPTION
**Pull request by chdemko**
See
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=24472

### CODE REVIEW

**Comment by Hackwar** [comment]
The problem with this is, that you can't overload the loadObject function anymore to change the behavior at a central point, for example to filter the input. Now you need to replace at least two methods.

**Comment by LouisLandry** [comment]
Christophe, in your issue you claim there is a performance improvement.  If it takes up 20% before, what does it take up after?  I tend to agree with Hannes here, unless we can assert that the object coming out of the stringToObject() methods is always acceptable as the internal data structure of a JRegistry object.  If that is the case then we are indeed doing double work.  Perhaps that is something worth exploring?

**Comment by chdemko** [comment]
In the test I have I've done 4-5 months ago, the performance gain was about
20% on the sample data. I will redo the tests and post here the results

2011/6/11 LouisLandry <
reply@reply.github.com>

**Comment by chdemko** [comment]
After doing benchmark (http://code.google.com/p/webgrind/) on sample data using the home page: here are the results
-JRegistry::loadString takes about 24% of the running time before applying patch (total time is 530 ms) on my laptop
-JRegistry::loadString takes about 4% of the running time after applying patch (total time is 424 ms) on my laptop

See
http://joomlacode.org/gf/download/trackeritem/24472/66248/Capture-webgrindof-home-chdemko-public_html-trunk-index.php-MozillaFirefox.png
http://joomlacode.org/gf/download/trackeritem/24472/66249/Capture-webgrindof-home-chdemko-public_html-trunk-index.php-MozillaFirefox-1.png

**Pull request merged**
