### PR TITLE
Joomla CMS [#25835, #26628] JTable:getInstance doesn't manage correctly multiple includePaths

### PR DESCRIPTION
**Pull request by chdemko**
See
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=25835
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26628
https://github.com/joomla/joomla-platform/issues/227

As was done for controllers when searching their models using their getModel method, the idea behind this patch consists to add several things:

JTable::addIncludePath
1. A call to JTable::addIncludePath() will return all paths previously added or the core tables folder of Joomla! (as it is before patch)
2. A call to JTable::addIncludePath('my/new/path') will add the new path to the global list and will return the global list (as it is before patch)
3. A call to JTable::addIncludePath('my/new/path', 'MyPrefixTable') will add the new path to the global list and to the 'MyPrefixTable' list and will return it

JTable::getInstance
1. Search using the prefix specific list using JTable::addIncludePath(null, $prefix)
2. Fallback to search in the global list of JTable::addIncludePath()

JModel::addTablePath

  have an optional second parameter to be passed to JTable::addIncludepath

JModel::__construct
1. can defined a table_prefix value
2. calls self::addTablePath using table_prefix as second parameter

### CODE REVIEW

**Comment by LouisLandry** [comment]
Would you be interested in helping us move to use JLoader::discover() instead of this include path stuff?  That would be a much cleaner and saner solution moving forward.

**Comment by chdemko** [comment]
Ok I'm going to do so

**Comment by chdemko** [comment]
New patch proposed that uses the JLoader::discover method

**Comment by eddieajau** [comment]
Nice work, but I'm going to put a hold on this one unit we establish unit tests to verify the change doesn't introduce any regression errors.

**Comment by elkuku** [comment]
**Checkstyle error details:**
libraries/joomla/application/component/controller.php:154
Return comment requires a blank newline after it
libraries/joomla/application/component/controller.php:1148
Additional whitespace found at end of file
libraries/joomla/application/component/model.php:548
Additional whitespace found at end of file
libraries/joomla/database/table.php:27
Missing class doc comment
libraries/joomla/database/table.php:1522
Additional whitespace found at end of file

**Comment by eddieajau** [comment]
Branch not merging cleanly.

**Comment by chdemko** [comment]
Closing this one. The MVC will be reworked after 11.4

**Pull request closed without merging**
