### PR TITLE
Update JHtmlForm::token() test

### PR DESCRIPTION
**Pull request by mbabker**
Update the test to mock the session due to a unit test failure locally, and use getFormToken in the test as well.

### CODE REVIEW

**Comment by elkuku** [comment]
This fixes the UT error on my side too.
Not sure why they would only appear "locally", but it works :)

**Comment by mbabker** [comment]
Well, they weren't showing up from Jenkins reports.  So, obviously, he's
got some super secret squirrelly stuff going on to keep from getting that
failure  ;-)

On 12/7/11 1:29 AM, "Nikolai Plath"
<reply+i-2459345-87575b293c399da6f106104af839bb02795b25c5-368545@reply.gith
ub.com> wrote:

**Comment by realityking** [comment]
The form.php stuff got added with #604.

**Comment by elkuku** [comment]
> So, obviously, he's got some super secret squirrelly stuff going on to keep from getting that failure ;-)

This is, honestly, the only reasonable explanation :P
The error also does not appear on the build server but the test gets executed - another JSecret&trade;...

**Comment by mbabker** [comment]
OK, so I've rebased the branch based on the merge of #604, so now all that's being done here is updating the unit test.

**Comment by LouisLandry** [comment]
Hotness.

**Pull request merged**
