### PR TITLE
Added a few test case for User (save/delete)

### PR DESCRIPTION
**Pull request by fanno**
Added: test case for delete
Added: test case for save
Removed: todo from testBind

I hope this one is working straight out of the box this time unlike last/first one.

is there some doc or something on how to setup a envioment to run the tests and so on my self to ensure it is working before making a pull request ?

I don't think http://docs.joomla.org/Joomla_CodeSniffer is that... ? as it seems to only be related to coding syntax.

Note, i assume that if i add the user for delete test in to the xml that will be the same as if it is in database ?

-Thanks

### CODE REVIEW

**Comment by mbabker** [comment]
http://joomla.github.com/joomla-platform/?appendices/analysis.md - That should help you get set up.

**Comment by fanno** [comment]
i use windows so seems i cant preform this task =(

**Comment by pasamio** [comment]
I don't see why Windows should cause any problems, we have plenty of people with Windows. Most of the tools install via PEAR and presuming you can get PEAR setup properly on Windows, you should be able to install almost everything else you need.

Looks like there is a unit test error, you will likely need to add that table definition to the `tests/schema/ddl.sql` file in the repository since it doesn't appear to be there right now:
http://developer.joomla.org/pulls/pulls/1745.html

**Comment by fanno** [comment]
anyway jos_messages_cfg ? i do not see where this comes from ? should this not only be using user table ?

i can see ofcause it is not there as you suggest.

this is a dump from the exsisting database is this then what should be there ? (j 2.5)

```
CREATE TABLE `jos_messages_cfg` (
  `user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `cfg_name` varchar(100) NOT NULL DEFAULT '',
  `cfg_value` varchar(255) NOT NULL DEFAULT '',
  UNIQUE KEY `idx_user_var_name` (`user_id`,`cfg_name`)
);
```

tho it looks different from what i see in the tests/schema/ddl.sql possible because it is a mysqli ?

if i had to guess i would say it should look like this 

```
CREATE TABLE `jos_messages_cfg` (
  `user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `cfg_name` varchar(100) NOT NULL DEFAULT '',
  `cfg_value` varchar(255) NOT NULL DEFAULT ''
);

CREATE UNIQUE KEY `idx_user_var_name` ON `jos_messages_cfg` (`user_id`,`cfg_name`);
```

I will see what i can do to get it installed and such (PEER and the php tester ...), i surely do no what to contribute a lot of code that just end up fail all the time.. because i cant really test it (at this time)

-Thanks

P.S
if databases need to be in tests/schema/ddl.sql and good reason why they all are not? not sure if there is a reason or not.

**Comment by pasamio** [comment]
The standard tests run against SQLite which has a slightly different syntax but is mostly compatible.

**Comment by fanno** [comment]
OK i have finally been able to setup PEAR and phpunit took about 6 hours .because of issues with PHP and Apache

i do not see error on JUserTest::testDelete -> http://developer.joomla.org/pulls/pulls/1745.html

maybe i am running it wrong but i am running it on the root of the directory joomla-platform 

i do see 38 other failures tho

-Thanks ?

**Comment by pasamio** [comment]
38 other failures seems strange, what are those failures?

**Comment by fanno** [comment]
not sure if i still have issues with my setup .. but this is one of the errors

24) JViewHtmlTest::testGetPath
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'C:\Users\fanno\data\Projects\workspaces\phpstorm\joomla-platform\tests\suites\unit\joomla\view/layouts2/olivia.php'
+'C:\Users\fanno\data\Projects\workspaces\phpstorm\joomla-platform\tests\suites\unit\joomla\view\layouts2\olivia.php'

in this case it happens because the forward slash are hardcoded .. and seems to be system depended ?

**Comment by fanno** [comment]
http://pastebin.com/T8BQmMC6

more here, are the results put in a log some where if you need it all ?

**Comment by fanno** [comment]
$this->assertEquals(**DIR** . '/layouts2/olivia.php', $this->_instance->getPath('olivia'));

**Comment by pasamio** [comment]
Try wrapping a realpath around the **DIR** portion. If that fixes things it might be worth another pull request to get that sorted for Windows testers. Seems strange that you aren't getting the error the pull tester is getting however, are you sure there aren't any uncommitted changes locally?

**Comment by fanno** [comment]
the only change i have is this pull request and the phpunit.xml

what do you mean with:
Try wrapping a realpath around the DIR portion ?

-Thanks

**Comment by pasamio** [comment]
Ok, so you haven't changed the ddl.sql file then. Strange!

What I was suggesting is this:

```
$this->assertEquals(realpath(__DIR__ . '/layouts2/olivia.php'), $this->_instance->getPath('olivia'));
```

**Comment by fanno** [comment]
no nothing else change because i wanted to start out by replicating the error and go from there.

**Comment by fanno** [comment]
yes the realpath() fix it tho of cause it pops up the next one ..

**Comment by elinw** [comment]
I don't know if you noticed that I have a pull request with a lot of JUser tests, but yay none of them are for save or delete. But you might want to look because we don't want to duplicate effort. #1736  This is great because there used to be 4% coverage and now we will be much higher.

**Comment by fanno** [comment]
hehe @elinw i am just using it as a lering experiance =) hopfully i will be able to also add something of value at one point =)

**Comment by fanno** [comment]
i have added a new pull request btw
https://github.com/joomla/joomla-platform/pull/1748

this pull request i am attempting to fix the tester to work on windows as well ... can consider this one on hold until i can preform the tests on this one my self =)

**Comment by fanno** [comment]
i would guess this is it:

``` php
    public function add($udiff, $root = JPATH_BASE, $strip = 0)
    {
        $this->patches[] = array(
            'udiff' => $udiff,
            'root' => isset($root) ? rtrim($root, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR : '',
            'strip' => $strip
        );

        return $this;
    }
```

i just do not know at this time how to fix it, at this time

**Comment by pasamio** [comment]
If you wrap code in triple back ticks, it'll flip the code highlighter on

**Comment by fanno** [comment]
I don't think i understand What you mean !  =(

**Comment by pasamio** [comment]
Sorry, I should have been clearer. When making a comment if you wrap code in three back ticks (`) on a single line followed by "php" and then put the code you want to add then later close it again with three back ticks (php isn't required here), GitHub will automatically style the code as PHP. If you don't put the PHP in, it'll do a generic formatted text block but if you edit your comment above you should be able to see what I mean. Click on the "Comments are parsed with GitHub Flavored Markdown" link above the comment box for more details.

**Comment by fanno** [comment]
thanks for the info =)

**Comment by fanno** [comment]
I have made changes locally to make this code not fail. But I am not done testing. I will commit it later today if time permits 

Will it cause conflicts because i merged in https://github.com/joomla/joomla-platform/issues/1748 to this one in order t run the test?

-Thanks

**Comment by fanno** [comment]
done i believe!

**Comment by fanno** [comment]
Am i missing something for this one ?
-Thanks

**Comment by elinw** [comment]
I think there is just a backlog and people are on holiday.

**Comment by fanno** [comment]
np =) just wanted to make sure =)

**Comment by eddieajau** [comment]
This PR is no longer mergable.

**Pull request closed without merging**
