### PR TITLE
Make more classes autoloadable.

### PR DESCRIPTION
**Pull request by realityking**
Remove some unnecessary jimport() calls.

### CODE REVIEW

**Comment by eddieajau** [comment]
Are the unit tests running ok your end?

**Comment by realityking** [comment]
Can't really check. My unit test set up is somehow broken, I really need to fix it.

**Comment by elkuku** [comment]
It says something like the autoloader fails to autoload ;) http://elkuku.github.com/pulltester/pulls/661

**Comment by realityking** [comment]
Is that from after my last push?

**Comment by elkuku** [comment]
It features a time stamp ;)
But it seems to be taken before your last push - now the error is different.. http://elkuku.github.com/pulltester/pulls/661

**Pull request merged**
